### PR TITLE
Hotfix - pg version on docker

### PR DESCRIPTION
**Pull request by nourspace**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
When installing using Docker `pg@7.x` is installed which has different API than `pg@6.x.`
Issue: #1041 

* **What is the new behavior (if this is a feature change)?**
It now installs a working version of node-postgres when using Docker

* **Other information**:
I tried migrating to `pg@7.x` and later decided not to as the deprecations touch many points and to make sure everything is correctly migrated I need more time.

### CODE REVIEW

**Comment by askmike** [comment]
Thanks for the PR, but why the linting? This is not how the rest of the codebase is styled ;)

**Comment by nourspace** [comment]
I tried to match the style but seems it didn't work out well. I think something like eslintrc would be great or some kind of doc to refer to like https://github.com/airbnb/javascript


Closed in favor of #1257

**Comment by askmike** [comment]
I agree about the outdated code style, though Gekko is an old project and the majority of the code was written a long time ago.

In newer projects I am using [prettier](https://github.com/prettier/prettier) which restyles all code to one common form, similar to the go fmt for golang. I might do that at some point for Gekko, but I am afraid I'll overwrite too many things that didn't change (messing up tools like git blame).

**Comment by nourspace** [comment]
Makes sense. I just wasn't sure what to do with things that obviously needed reformatting.
I will just ignore these in future PRs.

**Pull request closed without merging**
