### PR TITLE
Batch the backtest with variation in parameters, result in CSV

### PR DESCRIPTION
**Pull request by pprados**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This extension launch many times a back test, with different parameters.
All the results are added in a CSV file. It's easy to try different parameters values for the same data, or
to check a strategy in a sliding windows.

See `config.lab` in `sample-config.js`
To start, check the backtest
`node gekko --config <...> --backtest`
then use 
`node labgekko --config <...> --backtest`.
```
config.lab={
  enabled:true,
  file:"labs/"+config.tradingAdvisor.method+".csv",
  // Fields to add in CSV. Can be omitted or reorders
  fields:[
    "method", "exchange","currency","asset",
    "candleSize","historySize",
    "patchs",
    "startTime","endTime","timespan",
    "startPrice","endPrice","market","trades",
    "startBalance","balance","profit",
    "relativeProfit", "relativeResult"
  ],
  // Lists of modification to apply in config.
  patchs:[
    { 
      path: "MACD.short",
      loop: ["5", "<= 15", "+ 5"], // Normal:10
    },
    { 
      path: "MACD.long",
      loop: ["16", "<= 26", "+ 5"], // Normal:21
    },
    { 
      path: "MACD.signal",
      loop: ["8", "<= 10", "+ 1"], // Normal:9
    },
    {
      path:"backtest.daterange",
      exloop:[
        'config.{}={from:"2016-01-01", to: "2016-04-01"}',
        'moment(config.{}.to).isBefore("2017-12-15")',
        'slidingWindow(config.{},1, "month")',
        '// require nothing in global scope',
      ],
    },
  ],
}
```

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:
It's possible to add a new mode and remove the specific `labgekko`.

### CODE REVIEW

**Comment by askmike** [comment]
Good stuff, so the idea is that you have to specify all iterations you want to run in a config like so:

    patchs:[
      { 
        path: "MACD.short",
        loop: ["5", "<= 15", "+ 5"], // Normal:10
      },
      { 
        path: "MACD.long",
        loop: ["16", "<= 26", "+ 5"], // Normal:21
      },
      { 
        path: "MACD.signal",
        loop: ["8", "<= 10", "+ 1"], // Normal:9
      },
      {
        path:"backtest.daterange",
        exloop:[
          'config.{}={from:"2016-01-01", to: "2016-04-01"}',
          'moment(config.{}.to).isBefore("2017-12-15")',
          'slidingWindow(config.{},1, "month")',
          '// require nothing in global scope',
        ],
      },
    ],

Since 0.4 Gekko can act as a server with a REST api: you can start a the server (automatically started when you run the UI) and run backtests against it by passing a config, the server will return the result of the backtest.

What would you think of putting this functionality in a small standalone script that just calls the rest API of Gekko? :)

That way people how have different ideas about how to try out different parameters can do it differently, and we don't have to have big discussions about it in Gekko itself, see #767 for an example.

**Comment by decoye** [comment]
@askmike would you mind to share information on how to use the api to pass information to it?

**Comment by askmike** [comment]
@decoye #645 has an (outdated) example :)

**Comment by pprados** [comment]
Hello,

I think it's a good idea. Now, the code juste start a fork. But, it's possible to invoke the API.
Where is the version 0.4 ? Which tag ?

**Comment by imkane** [comment]
Neat stuff! This is what I had in mind awhile back but I wasn't smart enough to code it lol.

**Comment by imkane** [comment]
@pprados - I'm trying to figure out the purpose of the relativeProfit and relativeResult cols (which are always identical). They don't seem to match any output from the UI using the same test params. Any advice?

For example, in the CSV file:

method | RSI.interval | RSI.thresholds.low | RSI.thresholds.high | RSI.thresholds.persistence | market | trades | relativeProfit | relativeResult
RSI | 2 | 25 | 55 | 1 | -0.0169 | 98 | 0.2632 | 0.2632

And in the UI:

screenshot - 9_4_2017 10_02_08 am

(Notice that the # of trades don't even match)

**Comment by pprados** [comment]
Hello,
Check the candle size and history. Compare with the backTest.

The relativeProfit is just the result of the calculate report.
The relativeResult must be fixed to (balance-startBalance)-(endPrice-startPrice) to compare the market and the strategy. You must initialise the asset to zero.

**Comment by imkane** [comment]
@Pascal66 Yes, I've checked candle size and history. I still can't get the lab results, even just for "market" to match what the UI outputs. Weird.

Are you able to get your lab results to match your UI?

**Comment by imkane** [comment]
Also, how is it possible that "market" changes from test to test?

screenshot - 9_5_2017 11_35_30 am

**Comment by pprados** [comment]
For the "market change", I propose to use my another pull-request with unit test of strategies.

**Pull request closed without merging**
