### PR TITLE
Use script to generate market data for binance, karken and bitfinex and exchange function for lot sizing

### PR DESCRIPTION
**Pull request by cmroche**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature

* **What is the current behavior?** (You can also link to an open issue here)

Product entries are done by hand, for exchanges with many assets this is tedious and prone to human error.

getMinimumSize on portfolioManager doesn't handle Binance's lot size requirements correctly result in occasional errors when posting small orders.

* **What is the new behavior (if this is a feature change)?**

Binance market data is now moved to a second .js file, which is updateable with a script. The script parses the product definitions for all available pairs and adds them to the product list with all necessary information.

Added the function getLotSize to the exchange and updated portfolioManager to check for this function and use it is available for computing the correct lot size of an order. General rules are that if we are blow the minimum, we don't trade. This will allow any exchange to define necessary behaviour for lot sizing to that specific exchange.

* **Other information**:

If we are happy with this approach for managing market data I'll apply the change to Kraken and Bitfinex as well.

### CODE REVIEW

**Comment by cmroche** [comment]
This change is built on top of #1508, changes specific to this request start at 580fafd

**Comment by cmroche** [comment]
I submitted the same change for Kraken, as a bonus I was finally able to remove all the special handling code for newer assets. While not clearly documented in their AI, the returned API object keys actually give us the correct order book name for an asset pair queries.

**Comment by ms121** [comment]
@cmroche 
Tested although got the following error:

> 2017-12-26 16:07:17 (DEBUG):	[binance.js] (addOrder) BUY 1704.8631578947368 POE @0.00000189 BTC
> 2017-12-26 16:07:18 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: undefined
> 2017-12-26 16:07:18 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: [binance.js] undefined data: {"code":-1013,"msg":"Filter failure: LOT_SIZE"}

**Comment by cmroche** [comment]
@ms121 The undefined error suggst that you might be using a binance older than 1.1.0, could you check and confirm that please?

That aside, I'll look into why it tried to allow that order to go through, it clearly should have been prevented due to the lot size.

**Comment by cmroche** [comment]
@ms121 Should be fixed now.

**Comment by jessrbird** [comment]
@cmroche Sorry for another newb question, but what is the easiest way to download all the changed files in the "files changed" section, or otherwise update my gekko installation with these latest code changes? I've been copying and pasting the text, but I'm thinking there has to be a better way. Thanks!

**Comment by cmroche** [comment]
@jessrbird You cannot really download just the changed files, the easiest way to test a PR is to checkout or download the branch it is based on. In this case that would be here: https://github.com/cmroche/gekko/tree/origin/product_updates

If you are using GitKraken as your GIT client, it does have the ability to grab and apply PRs in the client. You would need to handle conflicts yourself, but should be minimal if you are based on the 'develop' branch. I am not an expert with GitKraken though, so I cannot offer much help with this.

**Comment by werkkrew** [comment]
I pulled this commit and ran the updateBinance.js script, the markets file looks correct.  When running it on actual trading I get the error:

> 2017-12-28 10:10:54 (DEBUG):    [binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
> 2017-12-28 10:10:54 (ERROR):    Wanted to buy ZEC but the amount is too small (0.000000000000) at binance
>

**Comment by cmroche** [comment]
@werkkrew Please update your binance module with `npm i binance@1.1.1` to fix the error reporting. I'll look at why it tried to buy with nothing.

**Comment by cmroche** [comment]
@werkkrew The error that you are seeing, that the amount was too small, is correct if the amount it is requesting is too small for the market LOT size. I've made some small changes though, changing the error to a warning and printing the original requested amount and price (not the adjusted) just in case the lot size calculation was wrong. If you update try again and let me know if the requested amount was actually larger than the minimum lot sizes.

**Comment by jessrbird** [comment]
@cmroche I downloaded the zip using the link you provided above to get the latest PR. Getting an error running tradebot at binance USDT/BCC pair. The bot tried to sell BCC, but BCC balance was already 0. Here is the error:

/home/money/gekko/plugins/trader/portfolioManager.js:236
      return log.warning(
                 ^

TypeError: log.warning is not a function
    at process (/home/money/gekko/plugins/trader/portfolioManager.js:236:18)
    at bound (/home/money/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.getLotSize (/home/money/gekko/exchanges/binance.js:215:12)
    at Trader.bound [as getLotSize] (/home/money/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.sell (/home/money/gekko/plugins/trader/portfolioManager.js:261:19)
    at Manager.bound [as sell] (/home/money/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.act (/home/money/gekko/plugins/trader/portfolioManager.js:169:16)
    at bound (/home/money/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/money/gekko/node_modules/async/dist/async.js:3853:9
    at /home/money/gekko/node_modules/async/dist/async.js:484:16
RECEIVED ERROR IN GEKKO 352640273213704

Let me know what you think.

**Comment by cmroche** [comment]
@jessrbird Bah, should be log.warn sorry.. will send a fix in a few minutes

**Review by Moun1r1 — APPROVED** [review]

**Comment by jessrbird** [comment]
@cmroche Going to try starting the trading bot now, but I noticed a problem. I can no longer import data from binance. Other exchanges seem to work. I can't find any errors or logs, but when I go to scan available data, I see: 

Unable to find datasets in the following markets:

- binance:USDT:BCC
- binance:USDT:BTC

**Comment by cmroche** [comment]
@jessrbird Binance changed their API about about 72 hours ago, this broke importing. PR #1568 is a fix for that problem.

**Comment by jessrbird** [comment]
@cmroche I tried using https://help.github.com/articles/creating-an-issue/ to submit a new issue, but I couldn't find the issues tab, nor a "new issue" button, so I'll submit my error here if that's okay. After two days of successful trading, I get this error:

/home/money/gekko/core/budfox/marketFetcher.js:94
      log.warn(this.exhange.name, 'returned an error while fetching trades:', err);
                            ^

TypeError: Cannot read property 'name' of undefined
    at Fetcher.processTrades (/home/money/gekko/core/budfox/marketFetcher.js:94:29)
    at bound (/home/money/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.processResults (/home/money/gekko/exchanges/binance.js:77:21)
    at bound (/home/money/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/money/gekko/core/util.js:28:7
    at /home/money/gekko/exchanges/binance.js:71:12
    at Request.request [as _callback] (/home/money/gekko/node_modules/binance/lib/rest.js:66:21)
    at Request.self.callback (/home/money/gekko/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
RECEIVED ERROR IN GEKKO 424488944948552
Child process has died.

Also, strangely, the exposure time displayed in round trips is saying months and years, instead of hours and minutes when using the tradebot. In backtesting, the times are listed accurately.

Thanks, and let me know if there is anything I can do to help!

**Comment by werkkrew** [comment]
@jessrbird Try to do 'npm i binance@1.1.2' and see if that helps.

**Comment by jessrbird** [comment]
@werkkrew I will try that. Thanks!

**Comment by cmroche** [comment]
@jessrbird There is a typo in the line `this.exhange.name` should be `this.exchange.name`. The issue is not related to this PR, and I saw that someone else submitted a PR for a fix a week ago or so. You could just fix it in place :)

**Comment by BossGrand** [comment]
Whats the status of this?

**Comment by mronus** [comment]
It seems that this commit includes solutions for several issues that we currently have. It would be great to have this merged asap 👍

**Comment by mboremski** [comment]
can confirm that.
This one worked for me to get binance working.
Would be happy to see this in develop soon.

**Comment by mronus** [comment]
I got the following exception several times when trying to run tradebot for ETH-EDO pair:

```2018-01-12 22:27:36 (DEBUG):	[binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
2018-01-12 22:27:36 (INFO):	Attempting to BUY 0.13090066539923953 EDO at binance price: 0.004187
2018-01-12 22:27:36 (DEBUG):	[binance.js] (addOrder) BUY 0.13 EDO @0.004187 ETH
2018-01-12 22:27:37 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: undefined
2018-01-12 22:27:37 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: [binance.js] undefined data: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
```

I guess that this commit solves this issue as well. @cmroche, please correct me if I am wrong.

**Comment by mboremski** [comment]
Tested multiple times, thanks to @cmroche no conflicts anymore..
Who can finally make this PR fly?

**Comment by askmike** [comment]
@cmroche apologies for the delays on this PR, it escaped my attention completely.

First note: I love this approach! I think it is important that Gekko only supports currencies whatever we release, and this way we stay in total control between release cycles.

Some quick questions/notes:

> Added the function getLotSize to the exchange and updated portfolioManager

Is this function required? Eg. will merging this break every other exchange (that does not have this implemented)? If so: I can work on making this optional.

> `exchanges/data/bitfinexMarkets.js`

For me personally it would be a lot more clear to call this file `exchanges/bitfinex-markets.json`: when looking at available exchanges only `.js` files are considered, on top of that JSON for generated static data makes more sense to me.

> `exchanges/data/update-binance.js`

What do you think about moving this to a util folder that can generate whatever is necessary (which for now means only market files).

**Comment by cmroche** [comment]
@askmike 

`getLotSize` is sort of necessary for Binance. They have a lot of rules about lot sizing, they could be expressed generically and add more properties to control in the portfolioManager, but I think the code would actually be more complicated in the end, and likely wouldn't be used anywhere else. By providing this function we can take more complicated cases of lot sizing techniques used by exchanges and allow them to be defined in the exchanges themselves which is potentially beneficial.

The function is option though. portfolioManager checks is the function exists, if it does then it uses the provided function, if not it falls back to the old behaviour. Documentation is updated to indicate that it is optional as well.

Changing to JSON is not a problem, I considered this but went with JS to be consistent with the config files. It makes sense to use JSON though, and putting them in another folder is no problem at all. `util` is sort of a busy folder right now and very code related, perhaps a `scripts` folder, or a `data` folder, or something else?

**Comment by askmike** [comment]
> The function is option though. portfolioManager checks is the function exists, if it does then it uses the provided function, if not it falls back to the old behaviour.

perfect!

---

testing this now, if it all seems to work and I will manually fix what I like to see different :)

**Comment by askmike** [comment]
works great! If you can merge this: https://github.com/cmroche/gekko/pull/3 I'll merge this PR :)

**Comment by cmroche** [comment]
@askmike Thanks :) Done.

**Comment by askmike** [comment]
Seems I didn't commit everything, note that this is commit is needed now: https://github.com/askmike/gekko/commit/8bf4670a54d9913c4d04a0a1cc6913ecef3302b4

**Comment by talvasconcelos** [comment]
@cmroche or anyone that can shed some light on this... 
I need, for a scanner/trader bot i'm building for Binance, to place some orders. Can't seem to figure out how to make it work with binance's requirements. Been lurking gekko's code, especially the exchange file for binance, but i can't seem to figure out how the roundAmount and the lotSize work with the place order method!! Math is not my strong point! Also i can't seem to find the file where the placeOrder is called to see how gekko is preparing the amount to pass to the method.

What i want to achieve is place a buy order, at market price would be nice, with the BTC amount available. Then when conditions are meet, place a sell order with the bought currency amount available. 

Can someone help out?

**Comment by zzmike76** [comment]
hello

has the fix been merged? i am still getting the MIN_NOTIONAL error even after updating the dev branch. should I open a new issue?

thanks

**Pull request merged**
