### PR TITLE
[BUGFIX] Fixes empty client on postgresql plugin

### PR DESCRIPTION
**Pull request by VegtMedia-Alex**
@askmike probably will need some more attention, because I am not able to find out why the client is empty?

https://github.com/askmike/gekko/issues/2503

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by askmike** [comment]
Yea this is not ideal: if client is undefined Gekko won't run the query and never run the next callback (basically freeze).

Instead of doing this, we should probably check the first `err` parameter (right now it seems ignored). Would you mind doing that instead? You can use `util.die` (import util first) to crash Gekko with the error. I guess it would be cleaner to actually wrap the pool exposed by `handle.js` in a function that checks the error and passes only proper connections on, but you can do either.

**Comment by VegtMedia-Alex** [comment]
Hi @askmike my node knowledge is basic. I am still learning, i will see what i can do.

**Comment by askmike** [comment]
@alexvandervegt no problem! If the client is not defined it means that postgresql encountered an error. Gekko should check that like so:

https://github.com/askmike/gekko/blob/daa4eb6dacb64b3d9571c4dff04e9af07606bcc1/plugins/postgresql/handle.js#L54-L56

(if there is a DB error Gekko can crash, since there isn't much Gekko can do if the DB is down).

**Comment by askmike** [comment]
Let me know if you rather have me fix it, but I'll keep this open so you can finish up the PR :)

**Comment by VegtMedia-Alex** [comment]
@askmike I think best would be if you fix this one. I have looked over and over but I am not able to see it yet :)

**Comment by askmike** [comment]
fixed here: fe8dbcd

**Comment by askmike** [comment]
If you run it again now Gekko will spit out why client is undefined (there was a postgres error along the way).

**Comment by ezgoProject** [comment]
@alexvandervegt how did you change the database from sqlite to postgresql

**Pull request closed without merging**
