### PR TITLE
BTC-e pairs 

### PR DESCRIPTION
**Pull request by hoddy**
Added in the new additions of ETH and DSH. Also removed old dead coins which are no longer traded on BTC-e (Announced here: https://btc-e.com/news/207 )

### CODE REVIEW

**Comment by askmike** [comment]
Looks great, thanks!

**Comment by hoddy** [comment]
Phew, thats my first ever commit I'm glad i did it right! Cheers

**Comment by askmike** [comment]
Awesome! Feels good, right?

I haven't tested it yet, but it looks good. (Once I tested some markets I will merge with the `stable` branch).

**Comment by hoddy** [comment]
Yeah!

Thanks for all your work on this its an epic tool! Let me know if I can help out at all, I'm not the greatest programmer in the world but I might be able to help with the repetitive easy tasks =D

**Comment by askmike** [comment]
Sounds great. I could definitely use some help. 

_Programming:_

The current things can be found in the [todo](https://github.com/askmike/gekko#todo). But besides those you can always work on adding another exchange, adding new indicators, trading strategies or adding a new plugin. For those things see the [contributing doc](https://github.com/askmike/gekko/blob/stable/CONTRIBUTING.md).

_Other things:_
- Gekko is changing fast and it would be good if you can test Gekko once in a while to see if anything breaks.
- Let me know what you are using Gekko for, or better: what are you missing and would like to see?

**Comment by hoddy** [comment]
Good to hear, I was looking into trying to build a new indicator, hopefully. I think i will have a go at tying to integrate a few more exchanges as-well.

I'll make sure i give it a regular test now and again to see if i can break it!

I'm using it at them moment (simulating currently until I'm brave enough to go live). Currently I'm running on BTC-E Trading ETH to BTC, just testing out the different indicators and trying to get a feel for what is the most responsive. I've been out of the trading game since LTC was up at 47EUR so I'm also trying to remember how to trade humanly too. Ideally the overall goal would obviously be to make a profit!

I'm assuming you use Gekko and have tailored it to a purpose, how do you use it?

_Features_ 
Look great so far I like the idea of the plugin's they seem to work well. I think that the web server would be great with a bit of polishing, If it could show a basic chart from data (just for sanity checking) and also current funds and profits from the trader, maybe a pause button to stop trading remotely.

Before I found this I found a similar trading bot called [BitBot](https://github.com/5an1ty/BitBot) Its not massively different but Gekko seems more advanced, however it has a setting to allow notifications on mobile devices through [Pushover](https://pushover.net/) which I thought was a nice feature.

**Comment by askmike** [comment]
> just testing out the different indicators and trying to get a feel for what is the most responsive.

If you are not running windows, you could look into TA-lib (you also can on windows, but you need Visual Studio to compile). It is now possible to use all TA-lib indicators (see the [full list](http://ta-lib.org/function.html)) in Gekko. However, there is not a lot of documentation yet. So if you need some help let me know.

> I'm assuming you use Gekko and have tailored it to a purpose, how do you use it?

When I started Gekko 3 years ago the main purpose was to start at learning how to do finance. Right now I am using Gekko for a couple of things like watching a lot of different markets (to gather statistics) and experimenting with strategies and indicators.

> Look great so far I like the idea of the plugin's they seem to work well. I think that the web server would be great with a bit of polishing

I am actually working on that now: I want the webserver to be more like a _command center_. You can use that interface to run Gekko's in different modes: 
- use it to run a few gekkos over some live markets to gather statistics.
- configure and a backtest in your browser and see the results on your screen.
- import exchange data right from your browser.

> Before I found this I found a similar trading bot called BitBot Its not massively different but Gekko seems more advanced

Awesome! I actually know @5an1ty quite well. Back in the day he used to help out with Gekko. But at some point he wanted to create his own bot. This was at a time where Gekko had a lot of problems (storing candles to disk was very buggy) and I did not have time to fix everything.

> however it has a setting to allow notifications on mobile devices through Pushover which I thought was a nice feature.

It is actually extremely easy to add in Gekko, you can create a plugin that broadcasts information going through Gekko (trade advice, price information) to pushover. See [this doc](https://github.com/askmike/gekko/blob/stable/docs/internals/plugins.md#implementing-a-new-plugin) on how to do that. Or look at the [mail plugin](https://github.com/askmike/gekko/blob/stable/plugins/mailer.js) (very similar plugin).

**Comment by hoddy** [comment]
> If you are not running windows, you could look into TA-lib (you also can on windows, but you need Visual Studio to compile). It is now possible to use all TA-lib indicators (see the full list) in Gekko. However, there is not a lot of documentation yet. So if you need some help let me know.

Thankfully, I'm on Ubuntu 16.04 so talib seems to work out of the tin so far, I defiantly look over the link into talib you sent though, it looks like you can possibly do quite a lot with it.

> When I started Gekko 3 years ago the main purpose was to start at learning how to do finance. Right now I am using Gekko for a couple of things like watching a lot of different markets (to gather statistics) and experimenting with strategies and indicators.

Well there should be interesting times coming with the whole halving of th BTC, that should make for some interesting data! I cant help but ask (even though i feel guilty that you have done all the work to find the answer and I march in and have done very little research so far) have you found the secret? lol or at least the most useful strategy for use with Crypto coin? (I'm cringing just from asking)

> I am actually working on that now: I want the webserver to be more like a command center. You can use that interface to run Gekko's in different modes: 

That sounds brilliant, exactly what i was thinking and more, look forward to seeing that!

> Awesome! I actually know @5an1ty quite well. Back in the day he used to help out with Gekko. But at some point he wanted to create his own bot. This was at a time where Gekko had a lot of problems (storing candles to disk was very buggy) and I did not have time to fix everything.

Small world! Its a good design but just isn't as good as Gekko in my opinion, well and mathematically in the small amount of testing I've done so far Gekko gives a larger gross profit.

> It is actually extremely easy to add in Gekko, you can create a plugin that broadcasts information going through Gekko (trade advice, price information) to pushover. See this doc on how to do that. Or look at the mail plugin (very similar plugin).

I might just look into doing that, as you say the mail app works just as well if your device has Push enabled so its just as easy.

**Comment by askmike** [comment]
> I defiantly look over the link into talib you sent though, it looks like you can possibly do quite a lot with it.

I saw your issue, will look at it asap!

> have you found the secret?

I have been doing this for quite a while, I am not sure there was one secret that worked before and still works (at least I have not found it yet).. As for returns, I while ago I did arbitrage and it is way easier way to make money (with almost no risk as well). The thing about arb is that it is very zero sum, you can't make a good open source one (since everyone will be using that and there will be no profit for anyone).

**Comment by hoddy** [comment]
Thanks, I'm still getting my head around node, its nice its just a bit different lol.

Arbitrage, thats interesting, though I would have thought it would be difficult in general trying to get your funds in and out of exchanges in short amounts of time. Still thats cool to know, I wouldn't have even thought of differences in exchanges until you said about it but of course there would be.

**Pull request merged**
