### PR TITLE
Added gemini exchange by reverse engineering bitfinex

### PR DESCRIPTION
**Pull request by KevTheRev13**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added support for Gemini exchange.

* **What is the current behavior?** (You can also link to an open issue here)
No support for Gemini Exchange.

* **What is the new behavior (if this is a feature change)?**
Will have support for Gemini exchange

* **Other information**:

The gemini api is intentionally almost identical to the bitfinex api, and so I was able to reverse engineer support for gemini on gekko. I forked an incomplete npm module that was building a node js wrapper and completed the functionality (the forked repo was dead, almost 2 years not answering pulls). After registering it, I placed the npm module reference in the package.json (you can view the gemini wrapper in my repos - very basic).

I have created a gemini exchange .js from a bitfinex template. It works fine on the paper trader and market watcher, and at some point I will hook up a trader bot to a Gemini sandbox accounts for full testing. Any tweaks I need to make after testing the trader bot I will commit to this branch and make another PR.

Full disclosure - I don't write js code haha. Please take a good hard look before including this in a stable branch. I would keep in develop for now, I should be able to test the trader bot within 2-3 weeks. If anyone wants to they are welcome to test it (and if needed tweak it) sooner.

Thanks!

### CODE REVIEW

**Comment by askmike** [comment]
Awesome stuff! I will test this out very soon (in the sandbox, since that is all I can access) :)

**Comment by askmike** [comment]
Quick question, why does the gemini wrapper needs this?

> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

https://github.com/KevTheRev13/gemini-exchange-coffee-api/blob/0271b70b3f63ae3211f6f49e7a400f007272bd2b/lib/gemini.js#L4

**Comment by KevTheRev13** [comment]
Hi @askmike 

Good deal. I would do it sooner but I've got some things at work that will keep me busy for awhile.

As for the NODE_TLS_REJECT, I have no idea :-) haha.

A quick google search shows me this, and it looks like a logical answer.
https://stackoverflow.com/questions/35633829/node-js-error-process-env-node-tls-reject-unauthorized-what-does-this-mean

**Comment by KevTheRev13** [comment]
Hmm, perhaps it would run without that line. That's something to test. I'd rather not disable nodejs from checking certs unless it is necessary.

That line was included in the project that I forked from. Worth looking into.

**Comment by askmike** [comment]
@KevTheRev13 I know what it means, which is why I brought it up. It can be quite dangerous since it will force node to ignore the SSL keychain (making it very easy to MiTM).

Sometimes exchanges mess up with their SSL certs and this is necessary. I will do some testing to see what is the case :)

**Comment by KevTheRev13** [comment]
@askmike Good catch. 

I looked all the way back (I'm using a fork of a fork for the wrapper) and the original wrapper was written for bitfinex, and it has this code.

It is unlikely that Gemini needs it then since it was put in all the way back then for bitfinex. If you are free to test it without and make the change, please do.

Gemini is supposed to be built like fort knox (whether it's true or good marketing is a different story). They have several licenses I haven't seen many other exchanges flaunt. I think their certs should be fine.

I will retreat back to my nice and organized java code for now... :-)

**Comment by KevTheRev13** [comment]
Not wanting to expose anyone using this code to any security vulnerabilities, I've updated the npm module in the wrapper repo, and ran it with gekko for a quick smoke test using a watcher. Looks fine.

Pushed the changes in the wrapper repo, and updated the version in this branch.

**Comment by askmike** [comment]
Hey! I am trying to run this, however some API methods are not available on the gemini wrapper library, leading to these kind of errors:

    2017-09-03 12:03:55 (DEBUG):  getting ticker, balance & fee from Gemini
    /Users/pear/projects/gekko/exchanges/gemini.js:102
      this.gemini.ticker(this.pair, process);
                  ^

    TypeError: this.gemini.ticker is not a function
        at Trader.getTicker (/Users/pear/projects/gekko/exchanges/gemini.js:102:15)
        at bound (/Users/pear/projects/gekko/node_modules/lodash/dist/lodash.js:729:21)
        at RetryOperation._fn (/Users/pear/projects/gekko/core/util.js:174:7)
        at RetryOperation.attempt (/Users/pear/projects/gekko/node_modules/retry/lib/retry_operation.js:97:8)
        at Object.retry (/Users/pear/projects/gekko/core/util.js:173:15)
        at Manager.setTicker (/Users/pear/projects/gekko/plugins/trader/portfolioManager.js:134:8)
        at bound (/Users/pear/projects/gekko/node_modules/lodash/dist/lodash.js:729:21)
        at /Users/pear/projects/gekko/node_modules/async/dist/async.js:3845:9
        at replenish (/Users/pear/projects/gekko/node_modules/async/dist/async.js:1030:17)
        at /Users/pear/projects/gekko/node_modules/async/dist/async.js:1034:9

Were you able to test this successfully?

EDIT: note I was testing a live trader on Gemini.

**Comment by KevTheRev13** [comment]
@askmike 

Yep, you are totally right. I assumed the wrapper I forked had the needed API methods, but I see it is missing a bunch. I'll update it when I get a chance. Thanks for testing it out.

**Comment by askmike** [comment]
No worries, let me know when you had the chance!

**Comment by KevTheRev13** [comment]
So I added the missing APIs (getPortfolio and getTicker), but it seems to be erroring out on GetPorfolio. I'm not entirely sure why, and I cant find much info in the logs.

Any ideas?

**Comment by KevTheRev13** [comment]
added a console.log(err) in the getPortfolio error section. 

image

**Comment by askmike** [comment]
I will have a look soon, away from home for a bit.

**Comment by KevTheRev13** [comment]
No worries. Just providing info. 

It seems the error in the screenshot above is fixed by modifying the api url on gemini.js (node_modules\gemini-exchange-coffee-api\lib). The sandbox has it's own api url, need to use this instead "https://api.sandbox.gemini.com"; . 

But, it is still returning "Gemini has returned an error, retrying..." and I tried dropping console.log(err) in a couple more places and couldnt pickup anything. 

Same reponse when I use the command line too. I'm not sure how best to capture the actual error message to see what's going on.

image

**Comment by askmike** [comment]
I am getting a different error here:

    2017-09-04 22:43:32 (INFO): 

    /Users/pear/projects/gekko/node_modules/gemini-exchange-coffee-api/lib/gemini.js:64
            return cb(new Error(result.message));
                   ^

    TypeError: cb is not a function
        at Request._callback (/Users/pear/projects/gekko/node_modules/gemini-exchange-coffee-api/lib/gemini.js:64:16)
        at Request.self.callback (/Users/pear/projects/gekko/node_modules/gemini-exchange-coffee-api/node_modules/request/request.js:123:22)
        at emitTwo (events.js:125:13)
        at Request.emit (events.js:213:7)
        at Request.<anonymous> (/Users/pear/projects/gekko/node_modules/gemini-exchange-coffee-api/node_modules/request/request.js:893:14)
        at emitOne (events.js:120:20)
        at Request.emit (events.js:210:7)
        at IncomingMessage.<anonymous> (/Users/pear/projects/gekko/node_modules/gemini-exchange-coffee-api/node_modules/request/request.js:844:12)
        at emitNone (events.js:110:20)
        at IncomingMessage.emit (events.js:207:7)

I can have a look if you want me to, but can you first push all the code you have so I can debug the same issues you are facing?

**Comment by KevTheRev13** [comment]
Hi @askMike

I got busy with work, so let's table this for now. If I get some free time I'll take a look and update this chain.

Thanks !

**Comment by askmike** [comment]
:+1:

**Comment by KevTheRev13** [comment]
Had a minute today, I think I have it working. 

I want to clean up the npm package readme and then I'll push/publish everything and let you know.

Thanks!

**Comment by KevTheRev13** [comment]
Hi @askmike 

I had a trader bot working for a few hours (see screenshot below)

EDIT: I feel I should note that these logs are from a TEST ACCOUNT on Gemini. Those USD and BTC numbers are purely in PLAY MONEY unfortunately. So any would be thieves will be dissapointed :-)
image

But, after doing some manipulations with my workspace I am now getting that callback error you showed above. No idea what happened between when I had it working and now.

Will look into it next weekend.

**Comment by KevTheRev13** [comment]
Interesting - right before that fails, the result has all correct data (console.log(result) right before cb).
image

**Comment by KevTheRev13** [comment]
@askmike 

I would be curious to hear your thoughts. All code is pushed.

That "cb is not a function" error has me stumped. I definitely had it working at some point because you can see it in one of my log files, but I can't figure out what changed to begin causing that error.

The result is coming through as expected, so I'm not sure where the error is.

EDIT: To use the sandbox, you need to change the npm package's lib/gemini.js url to "https://api.sandbox.gemini.com"; . The code pushed has the regular exchange url.

**Comment by askmike** [comment]
Sorry for the delayed response, will test this ASAP!

A sidenote on the screenshot of the logs (in notepad). The log lines should be on new lines (the same as in the terminal). If you open the logs in anything else than notepad (notepad++, sublime, etc) does the log appear better formatted?

**Comment by KevTheRev13** [comment]
Hi @askmike 

No worries, thanks.

And yea, they look fine in fancier text editors. Sometimes notepad is just a little quicker for me depending on what I'm doing. I have viewed these logs in TextPad and VS Code and they look as expected (Textpad below).

EDIT: I feel I should note that these logs are from a TEST ACCOUNT on Gemini. Those USD and BTC numbers are purely in PLAY MONEY unfortunately. So any would be thieves will be dissapointed :-)
image

**Comment by askmike** [comment]
@KevTheRev13 apologies for the long delay. I just had some time to test this but the sandbox is down. I've tweeted Gemini about it: https://twitter.com/mikevanrossum/status/914170575995719680

**Comment by KevTheRev13** [comment]
@askMike No worries.

Yes it looks like scheduled maintenance has gone on longer than expected. They actually have weekly maintenance I believe.

**Comment by askmike** [comment]
Thanks a lot! And apologies for the delay..

**Comment by KevTheRev13** [comment]
Hi @askmike 
No worries, good catch on the missing parameter in the api call in the npm module. Thanks for your help.

**Pull request merged**
