### PR TITLE
Inject config into his strategy

### PR DESCRIPTION
**Pull request by oktapodia**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature: To avoid injecting all the config file and then filter it by the strategy name, I did a little change to inject it directly through the Base strategy. This modification permits you to access to your `settings` configuration and also the `tradingAdvisor` configuration.

* **What is the current behavior?** (You can also link to an open issue here)
Today, we have to do 
```
var config = require('../core/util.js').getConfig();
var settings = config.UO;
```

* **What is the new behavior (if this is a feature change)?**
With this PR, we could do 
```
method.init = function() {
  this.settings // Get the strategy settings
  this.tradingAdvisor // Get the trading advisor 
}
```

* **Other information**:
How do I do the test? I did not see any tests for the strategies, do you have some advice because I'm not totally confident with the library

### CODE REVIEW

**Comment by askmike** [comment]
:o very nice, great stuff!

Would you mind updating the documentation here: https://github.com/askmike/gekko/blob/develop/docs/strategies/creating_a_strategy.md#configurables

Thanks!

**Comment by oktapodia** [comment]
@askmike Updated, and how about the testing?

**Comment by askmike** [comment]
Unit tests? Not the full codebase is under unit test at the moment, mainly indicator calculations and core components. This logic you changed was not under unit test right now, you are free to write unit tests for them if you want.

I'll do some manual testing myself before I merge (ASAP).

Thanks a lot already!

**Comment by oktapodia** [comment]
Hum ok I'll look into that after this PR :D

**Comment by askmike** [comment]
Thanks a lot :)

**Pull request merged**
