### PR TITLE
Fix links to point current (0.2) branch instead of master branch

### PR DESCRIPTION
**Pull request by bugron**
To keep documentation always up to date in this branch.
@askmike for future, I think it is a good idea to change your branching model. Gekko won't be 0.2 forever thus when you move to next version (hopefully, 1.0.0) these links need to be updated again to point to current renamed branch.
So my suggestion is archive `master` branch by renaming it something like `old-gekko` or whatever, then checkout new `master` from current `0.2` branch, rename `0.2` to `staging` or `developement`.
So the result is `staging` or `developement` branch (formerly `0.2`) is where all development goes, new features, bug fixes etc., `master` branch (formerly latest `0.2`) is where latest stable code is pushed from current development branch. So develope in `staging` and once code is stable, push to `master`.
**Note**, if you decide to do that now, then you'd to that before merging this PR **BUT** after you handle all other PRs (merge/close them), otherwise links in new `master` branch will point to `0.2` branch which won't exist anymore after renaming is done.

And another question. Those three PRs are open against current `master` branch which is obsolete. Should we close them and open new PRs against `0.2` branch?

### CODE REVIEW

**Comment by askmike** [comment]
My goal was to phase out the existing master branch (and go forward using the current 0.2 branch under a new name) rather soon (this week or next). There are only some things that needed to be fixed before we could clean up the old master branch:
- [x] Make sure a number of exchanges are working (a week ago only bitstamp was working).
- [x] Make sure all old plugins are working (or that non working ones are documented).
- [x] Make sure all docs (especially regarding plugins) are up to date.
- [x] Make sure the new branch is stable (no memory leaks, etc.)
- [x] Either merge of close all opened PRs

But you are right that this transition phase could be a little cleaner.

---

> Note, if you decide to do that now, then you'd to that before merging this PR BUT after you handle all other PRs (merge/close them), otherwise links in new master branch will point to 0.2 branch which won't exist anymore after renaming is done.

I am merging this is in now regardless since I'd rather have a consistent state (instead of half the links pointing to one branch and the other half pointing to a different one). As soon as we rename this branch to master we can fix them again.

---

> So my suggestion is archive master branch by renaming it something like old-gekko or whatever, then checkout new master from current 0.2 branch, rename 0.2 to staging or developement.
> So the result is staging or developement branch (formerly 0.2) is where all development goes, new features, bug fixes etc., master branch (formerly latest 0.2) is where latest stable code is pushed from current development branch. So develope in staging and once code is stable, push to master.

I think it's better to go forward without the branch name "master" to minimize confusion for people updating old gekko clients. What do you think of the following?
- `gekko-old` (current master)
- `develop` (develop branch, edge of current 0.2)
- `stable` (current 0.2)

I'll see how fast I can fix the issues in the above list to rename the 0.2 branch to "stable". The last item on the list is what stopped me from renaming the current "master" branch, I am afraid what will happen to those PRs (only 2 left now).

**Comment by bugron** [comment]
> ```
> gekko-old (current master)
> develop (develop branch, edge of current 0.2)
> stable (current 0.2)
> ```

Sounds good to me.
About those two PR's. Currently I know almost nothing about trading, trading algorithms, I'm not familiar with all this so I can't QA or test https://github.com/askmike/gekko/pull/272 but I definitely want to see https://github.com/askmike/gekko/pull/218 merged.

**Comment by askmike** [comment]
I now created two branches:
- stable
- develop

All links point to the stable branch (unless it is about something that changed in the develop branch). The 0.2 branch is now deleted.

**Comment by bugron** [comment]
Awesome!

**Comment by bugron** [comment]
Awesome! And `develop` needs to be the default branch so all PRs will be opened by default against that branch.

**Comment by askmike** [comment]
I rather add that to a `CONTRIBUTING.md` doc (see [here](https://github.com/blog/1184-contributing-guidelines)), mainly all Gekko users (who rather have the most stable version) want a stable version (should be the default). If you know what you are doing (eg. contributing or experimenting), try out the develop branch.

**Comment by bugron** [comment]
From my previous experience i know that only a small part of contributors read contribution guidelines. So lots of people were opening PRs against stable branch and I wrote a bot which points them what did they do wrong and checks if the opened PR follows repo's contribution guidelines.
Anyways, the decision is yours.

**Comment by askmike** [comment]
I get a few pull requests a week max. But Gekko has over 150 downloads a week. I rather have all these people downloading the stable version.

**Comment by bugron** [comment]
Awesome, sound reasonable to me :+1:

**Pull request merged**
