### PR TITLE
Added getOrder for btc-markets exchange

### LINKED ISSUE #935: No getOrder function for btc-markets exchange
The trader for btc-markets throws the following error

/home/ubuntu/gekko/plugins/trader/portfolioManager.js:355
    order => next => this.exchange.getOrder(order, next)
                                   ^

TypeError: this.exchange.getOrder is not a function
    at next (/home/ubuntu/gekko/plugins/trader/portfolioManager.js:355:36)
    at /home/ubuntu/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/home/ubuntu/gekko/node_modules/async/dist/async.js:1030:17)
    at /home/ubuntu/gekko/node_modules/async/dist/async.js:1034:9
    at eachOfLimit (/home/ubuntu/gekko/node_modules/async/dist/async.js:1061:22)
    at /home/ubuntu/gekko/node_modules/async/dist/async.js:1066:16
    at _parallel (/home/ubuntu/gekko/node_modules/async/dist/async.js:3844:5)
    at Object.series (/home/ubuntu/gekko/node_modules/async/dist/async.js:4663:3)
    at Manager.relayOrder (/home/ubuntu/gekko/plugins/trader/portfolioManager.js:358:9)
    at Manager.bound [as relayOrder] (/home/ubuntu/gekko/node_modules/lodash/dist/lodash.js:729:21)

### PR DESCRIPTION
**Pull request by upsatish**
Fixes #935

### CODE REVIEW

**Comment by askmike** [comment]
Hey @anotherkabab,

Some context: Since 0.5 the trader was updated and it now requires two changes:

- the getOrder method - it should return a specific object specified here: https://gekko.wizb.it/docs/extending/add_an_exchange.html#getOrder
- the cancelOrder method now takes a callback.

I've failed to do this for all exchanges, so some (including btc-markets) are now outdated. We would need to fix both issues above before we can add it back!

**Comment by upsatish** [comment]
Hi @askmike thank you for the review. I'll do those changes as you suggested.

Is there any way to test this apart from running the trader live?

**Comment by askmike** [comment]
I haven't found any, since it's all about dealing with real response data from the exchange. Some exchanges provide a sandbox API, if btc-markets does this that would be an option.

**Comment by askmike** [comment]
Closing this for inactivity.

**Comment by upsatish** [comment]
Sorry, wasn't able to complete this.

**Pull request closed without merging**
