### PR TITLE
changed btc-e to wex.nz and added all new pairs #1140

### PR DESCRIPTION
**Pull request by krieghof**

### CODE REVIEW

**Comment by krieghof** [comment]
Haven't rebuild the UI but it shows up in the UI, why?

**Comment by askmike** [comment]
Because the documentation is outdated, you don't need to rebuild the UI anymore to change the exchanges since everything is pulled from the rest API (where before it got compiled into the UI).

Great stuff, thanks! Would you mind also update this table: https://github.com/askmike/gekko/blob/stable/docs/introduction/supported_exchanges.md

**Comment by krieghof** [comment]
@askmike Table is now up to date

**Comment by askmike** [comment]
Thanks for the PR. It looks great but I am unable to install the dependencies (`node-uuid` which is needed by `request` which is needed by `node-wex`), maybe upading the request version in `node-wex` would help?

Anyway here is the output when I try to run:

    ➜  gekko git:(krieghof-develop) ✗ node -v
    v8.0.0
    ➜  gekko git:(krieghof-develop) ✗ npm i node-wex@1.0.2
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
    + node-wex@1.0.2
    updated 1 package in 2.998s
    ➜  gekko git:(krieghof-develop) ✗ node gekko -c config.js
    
      ______   ________  __    __  __    __   ______
     /      \ /        |/  |  /  |/  |  /  | /      \
    /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
    $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
    $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
    $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
    $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
    $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
     $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

    Gekko v0.5.7
    I'm gonna make you rich, Bud Fox. 


    2017-09-30 18:42:25 (INFO): Setting up Gekko in realtime mode
    2017-09-30 18:42:25 (INFO): 
    2017-09-30 18:42:25 (INFO): Setting up:
    2017-09-30 18:42:25 (INFO):    Candle writer
    2017-09-30 18:42:25 (INFO):    Store candles in a database
    2017-09-30 18:42:25 (INFO): 

    2017-09-30 18:42:25 (INFO): Setting up:
    2017-09-30 18:42:25 (INFO):    Trading Advisor
    2017-09-30 18:42:25 (INFO):    Calculate trading advice
    2017-09-30 18:42:25 (INFO):    Using the strategy: toggle-advice
    module.js:487
        throw err;
        ^

    Error: Cannot find module 'node-uuid'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/pear/projects/gekko/node_modules/node-wex/node_modules/request/request.js:17:12)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)

**Comment by krieghof** [comment]
Thanks for the tip, now it should work

**Comment by askmike** [comment]
Looks great! Thanks!

**Comment by haccg** [comment]
I'm missing the USD / USDT Pair

Tried to add it at in the markets, but I keep receiving this error:

 ERROR: Gekko only supports the assets [ BTC, LTC, NMC, NVC, USD, EUR, PPC, DSH,
 ETH, USDET, RURET, EURET, BTCET, LTCET, ETHET, NMCET, NVCET, PPCET, DSHET, BCHE
T ]  at wex.nz (not USDT)


What else do I have to do?

Thanks in advance!

**Comment by askmike** [comment]
@haccg it needs to be in all the following:

- the currencies list: https://github.com/askmike/gekko/pull/1148/files#diff-09874a956812fb4a568794b754240da7R244
- the assets list: https://github.com/askmike/gekko/pull/1148/files#diff-09874a956812fb4a568794b754240da7R245
- the markets list: https://github.com/askmike/gekko/pull/1148/files#diff-09874a956812fb4a568794b754240da7R249

**Comment by haccg** [comment]
@askmike 👍 
Thank you. Was missing it at the assets list.
Seems to work now.

**Pull request merged**
