### PR TITLE
[WIP] Release new stable version (0.4)

### PR DESCRIPTION
**Pull request by askmike**
First focus is stability (this PR), with experimental UI. Next release will be stable UI.

More info about the UI can be found in #489 and #513.

We can merge after:

CLI (legacy) interface:

- [x] make sure live market works
  - [x] make sure live trading works
  - [x] make sure paper trading works
- [x] make sure backtesting works
- [ ] verify whether all adapters work.

UI interface (new default):

- [x] merge ui-watchers into develop (even though it's WIP)
- [x] finish UI watchers:
  - [x] finish strat runner interface (show trades in price graph)
  - [x] show profit report (for paper trader)
- [x] make sure backtesting works
- [x] make sure backtesting talib works (UI, see [here](https://github.com/askmike/gekko/issues/489#issuecomment-285776325))
- [x] rewrite docs, default to UI
- [x] Add basic UI feedback
  - [x] modal when gekko backend is down.
  - [x] message when a live gekko crashes or cannot start.
- [x] force sqlite adapter (for now, see #625).

### CODE REVIEW

**Comment by chriscrutt** [comment]
at any point will Gekko support Coinbase?

**Comment by askmike** [comment]
@chriscrutt Gekko has support for GDAX (the exchange of coinbase), but there are a few bugs at the moment.

**Comment by askmike** [comment]
Strat runner now looks like this:

screen shot 2017-03-24 at 19 27 40

What I still want in there:

- profit report
- amount of trades
- visualize trades in chart

It will be very basic for now, but it will serve it's purpose :)

**Comment by askmike** [comment]
Profit report inside the strat runner looks like this:

screen shot 2017-03-25 at 20 41 43

**Pull request merged**
