### PR TITLE
Add function for send notification from strategy

### PR DESCRIPTION
**Pull request by thanhlmm**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
#2284

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
```
this.notice('Hello, I can send additional information here!');
```
To send a notification from my strategy file

* **Other information**:

### CODE REVIEW

**Comment by askmike** [comment]
Hey @thanhlmm, thanks for the PR!

I like this idea, just a few tiny things:

- can we call it something else than "notification"? It's not very descriptive that it can only come from a strategy. Maybe something like "strategyNotification" or "strategyMessage" (also instead of notice we can have notify).
- can you add it to the docs here: https://github.com/askmike/gekko/blob/develop/docs/internals/events.md

**Comment by askmike** [comment]
Also we probably need to think about how we want those to behave during backtests, if these notifications are for realtime stuff they should probably be ignored before even being propagated.

What kind of notifications do you feel like sending?

**Comment by askmike** [comment]
fixes #2284.

**Comment by thanhlmm** [comment]
> can we call it something else than "notification"? It's not very descriptive that it can only come from a strategy. Maybe something like "strategyNotification" or "strategyMessage" (also instead of notice we can have notify).

`this.notify('Somethings');` is a nice name !

> can you add it to the docs here: https://github.com/askmike/gekko/blob/develop/docs/internals/events.md

Sure then

> Also we probably need to think about how we want those to behave during backtests, if these notifications are for realtime stuff they should probably be ignored before even being propagated.

It rarely when user config any notification (email, slack,...) while backtesting but we should handle this case. I think we should have a config for determining if users should send `strategyNotification` while backtesting or not. In paper trade or real trade mode, I sure they will need `strategyNotification` to work.

How do you think, @askmike ?

**Comment by askmike** [comment]
Can you give an example of a notification you want to send?

**Comment by thanhlmm** [comment]
I use `Gekko` as a tool to watch market and give advice. So that, I need more information about what is happening like:
"We got 10 green candles, should we go long?"
"RSI is going beyond 120, MACD diff is now 20,..."

Or sometime user wanna get information of what is about to go like
"I detect an uptrend, wait for 2 more confirm candles to go `Long`"

**Comment by askmike** [comment]
That makes sense, and in that case it makes sense to have the possibility of having them available in backtests (to plot the notifications on a chart or so).

> this.notify('Somethings'); is a nice name !

For the inside strat? Yes that's great.

> strategyNotification

I like this one for the event name! Do you feel like fixing these names in a commit? After that (& added to the event doc) I can merge it :)

**Comment by thanhlmm** [comment]
Ok, I will make new pull request soon

**Comment by askmike** [comment]
You don't have to perse, you can push new commits to your branch `feature-notification` and they will be automatically show up here. If you run into anything just let me know.

**Comment by thanhlmm** [comment]
Hey @askmike ,
I have just edit some code base on your idea.
I changed `strategyNotification` event name to `stratNotification` for the same naming convention in your code base.

**Comment by askmike** [comment]
great stuff! Thanks a lot :)

**Comment by askmike** [comment]
great stuff! Thanks a lot :)

**Comment by thanhlmm** [comment]
I'm glad to contribute for great product 😎

**Pull request merged**
