### PR TITLE
Different select boxes for assets and currencies for the importer

### PR DESCRIPTION
**Pull request by tudorconstantin**
This PR is the implementation for issue #705 that I just opened.

### CODE REVIEW

**Comment by tudorconstantin** [comment]
I think the only way to get rid of the conflict in the build.js file is to re-generate the file after merging the pull request

**Comment by askmike** [comment]
Thanks for this!

funcOK but the commits are not really that clean, would it be possible to fix that by either rebasing or cherrypicking into a new branch? That should also solve the conflict in the compiled frontend

**Comment by tudorconstantin** [comment]
I'm glad you also find this useful.

I submitted a totally [new PR](https://github.com/askmike/gekko/pull/707), containing 2 commits:
- one with the modified source files
- one with the overwritten build.js file.

**Comment by askmike** [comment]
closed in favor of #707 .

**Pull request closed without merging**
