### PR TITLE
Fix sharpe ratio formula

### PR DESCRIPTION
**Pull request by MatSchaeff**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)   

Fix the sharpe ratio formula (missing brackets).   

sharpe ratio formula

### CODE REVIEW

**Comment by thegamecat** [comment]
Top work Mat!

**Comment by generalectric** [comment]
Excellent find!

**Comment by askmike** [comment]
Damn, nice find. Can you please rebase this on top of develop branch? If not I can manually pull this commit in.

**Comment by MatSchaeff** [comment]
You just did right ?
Or I need to do something else ?
(I'm not really familiar with git except for push and pull..)
I tried to rebase but conflict with this Dockerfile commit.
Should I remove it from the PR btw ?

**Comment by askmike** [comment]
I've done it now. Thanks a lot for your contribution! This was quite an important find.

**Pull request merged**
