### PR TITLE
Feature/fix floating bug in gdax

### LINKED ISSUE #922: GDAX trade error: size too precise
I got this error as Gekko was trying to trade on GDAX with a size that has 17 decimals.

```
2017-08-05 18:07:41 (ERROR):    Error buying at GDAX: { message: 'size too precise (0.55431682711244915)' }
```
(numbers are changed for privacy reasons)

I made the following modifications
```
# exchanges/gdax.js
# [...]
Trader.prototype.buy = function(amount, price, callback) {
    var args = _.toArray(arguments);
    var buyParams = {
        'price': parseFloat(price).toPrecision(8),
        'size': parseFloat(amount).toPrecision(8),
        'product_id': this.pair,
        'post_only': this.post_only
    };

    var result = (err, data) => {
        if(err) {
            log.error('Error buying at GDAX:', err);
            return this.retry(this.buy, args);
        }
        callback(err, data.id);
    }

    this.gdax.buy(buyParams, this.normalizeResult(result));
}

Trader.prototype.sell = function(amount, price, callback) {
    var args = _.toArray(arguments);
    var sellParams = {
        'price': parseFloat(price).toPrecision(8),
        'size': parseFloat(amount).toPrecision(8),
        'product_id': this.pair,
        'post_only': this.post_only
    };
    var result = function(err, data) {
        if(err) {
            log.error('Error selling at GDAX:', err);
            return this.retry(this.sell, args);
        }
        callback(err, data.id);
    }.bind(this);

    this.gdax.sell(sellParams, this.normalizeResult(result));
}
# [...]
```

Specificallly, in both price and size:

```
        'price': parseFloat(price).toPrecision(8),
        'size': parseFloat(amount).toPrecision(8),
```

Not sure if their API does allow 8 decimals, will report back when Gekko makes my first trade. May take a while, my strategy makes about one trade every 2 days.

### PR DESCRIPTION
**Pull request by wingleung**
Fixes #922

### CODE REVIEW

**Comment by askmike** [comment]
Hey,

The function is now never passed the second argument (decimalLimit), but as soon as I do the output doesn't make sense anymore. Example:

     Trader.prototype.getMaxDecimalsNumber(132.123, 2); // "132.12299999"

if you need a dynamic amount of demicals, what is wrong with `toFixed()` (after a math.floor since to fix does a normal round)?

**Comment by wingleung** [comment]
@askmike thanks for the review, indeed there was still a bug in other use cases. I fixed it in the following commit.

As for just using toFixed(), problem is setting toFixed(decimalLimit) will round up/down if the number has more decimals already. Math.floor() will only work if your multiplier is also dynamic, which I did do in the last commit. So it should work now...
`
 Trader.prototype.getMaxDecimalsNumber(132.123456789); // "132.12345678"
`
`
 Trader.prototype.getMaxDecimalsNumber(132.129, 2); // "132.12"
`
`
 Trader.prototype.getMaxDecimalsNumber(132.123, 2); // "132.12"
`

So to solve this... 
- we make the float number an integer by multiplying it (1e8 for 8 decimals, 1e2 for 2 decimals,...) so that the Math.floor will do its rounding down.
- divide by the same multiplier so it's a float number again
- toFixed(decimalLimit), to cut away all unnecessary decimals

Also fixed a bug where the config.post_only property would not set false when set to false.

**Comment by askmike** [comment]
Looks great! Let's hope this gets rid of the error :)

**Comment by askmike** [comment]
@damianleung it is still not working unfortunately, see #992.

**Pull request merged**
