### PR TITLE
Update documentation 

### PR DESCRIPTION
**Pull request by wakandan**
* add configuration section

### CODE REVIEW

**Comment by askmike** [comment]
Hey @wakandan so there are two ways of running Gekko:

- UI
- CLI

I want the UI to be the default, if users don't know Gekko and are looking for configuration options I want everything to be aimed at configuring Gekko for UI usage. So I don't want to add anything to a default configuration page that talks about `sample-config` and setting up that config.

The idea is: We need to keep everything as simple as possible for new users, and remove anything that might be unrelated and add confusion. The UI was designed to be this simple starting point so all current documentation (not found in the commandline folder) is aimed at this, as well as installation instructions (and docker files). You really only need to use the CLI for:

- Running a Gekko 24/7 for one of the plugins (IRC bot, telegram bot, etc).
- Developing new strategies (not necessary, but probably easier).
- Running a tradebot and requiring advanced logging.

I consider all these uses very advanced, so I don't want to throw configuration for that in people face when they have no experience with Gekko.

**Comment by wakandan** [comment]
Ok I will update the document to something along the line "for starter, UI mode can be run without any extra configuration. However if you wish to see the logs in UI mode or take advantage of advanced features of the CLI mode, you can do so by modifying the config file". Sounds good?

**Comment by askmike** [comment]
> Sounds good?

Hope you were not waiting for me!

Sounds great, but note the overlap between the configuration folder and the installation folder now, not sure what the difference is (since "installing gekko" is downloading files from github).

> UI mode can be run without any extra configuration

This is true, but the UI can also be configured (port, host, etc).

**Comment by askmike** [comment]
Closing this for inactivity.

**Pull request closed without merging**
