### PR TITLE
[DEBUG] Fix bitfinex sticky order

### PR DESCRIPTION
**Pull request by askmike**
See #2226.

If you experience issues on BFX please help us test this branch! Read this: https://gekko.wizb.it/docs/installation/updating_gekko.html#Updating-the-develop-branch

And run the commands, but replace `git checkout develop` with `git checkout hotfix/bfx-sticky`. As soon as it get stuck again, please post logs!

### CODE REVIEW

**Comment by nervousfinger** [comment]
Hi, 
Gekko got stuck again while buying on bitfinex, here is part of my log:

2018-08-22 02:53:46 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-22 02:53:47 (DEBUG):    No new trades.
checkOrder resp: { id: xxxx,
  cid: xxxx,
  cid_date: '2018-08-22',
  gid: null,
  symbol: 'etpusd',
  exchange: 'bitfinex',
  price: '2.9131',
  avg_execution_price: '0.0',
  side: 'buy',
  type: 'exchange limit',
  timestamp: '1534906268.0',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: 'xxxx',
  remaining_amount: 'xxxx',
  executed_amount: '0.0',
  src: 'api' }
2018-08-22 02:54:06 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-22 02:54:07 (DEBUG):    Processing 1 new trades. From 2018-08-22 02:53:51 UTC to 2018-08-22 02:53:51 UTC. (a few seconds)
2018-08-22 02:54:26 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-22 02:54:27 (DEBUG):    Processing 3 new trades. From 2018-08-22 02:54:14 UTC to 2018-08-22 02:54:15 UTC. (a few seconds)
2018-08-22 02:54:46 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-22 02:54:47 (DEBUG):    Processing 5 new trades. From 2018-08-22 02:54:41 UTC to 2018-08-22 02:54:41 UTC. (a few seconds)
2018-08-22 02:54:54 (DEBUG):    [ORDER] statusChange: MOVING
bfx cancel
2018-08-22 02:55:06 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-22 02:55:07 (DEBUG):    No new trades.

My order was fully executed at 02:54:41 and gekko tries to cancel the no longer existing trade at 02:54:54 and gets no response...

**Comment by askmike** [comment]
@nervousfinger thanks for the report!

> checkOrder resp: { id: xxxx,

I didn't log the time of checkOrder, but juding by the response this was before `02:54:41`. That means that the order was filled while gekko was cancelling, and gekko should have handled that.

> bfx cancel

Gekko fired a cancel, however no responce was logged. That can only happen because of:

- bfx didn't reply to our cancel request (unlikely)
- there was an error and Gekko completely swallowed it. Which is very strange...

Unfortunately I am unable to fix it based on that information.. I pushed more debug logging would you mind running it again?

**Comment by nervousfinger** [comment]
Hi Mike,
happened again today while selling:

2018-08-29 12:29:50 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-29T12:29:50.548Z 'checkOrder'
2018-08-29 12:29:50 (DEBUG):    No new trades.
2018-08-29T12:29:50.677Z 'checkOrder resp:' { id: xxxx,
  cid: xxxx,
  cid_date: '2018-08-29',
  gid: null,
  symbol: 'etpusd',
  exchange: 'bitfinex',
  price: '3.3826',
  avg_execution_price: '0.0',
  side: 'sell',
  type: 'exchange limit',
  timestamp: '1535545742.0',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: 'xxxx',
  remaining_amount: 'xxxx',
  executed_amount: '0.0',
  src: 'api' }
2018-08-29 12:30:10 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-29 12:30:10 (DEBUG):    No new trades.
2018-08-29 12:30:30 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-29 12:30:30 (DEBUG):    No new trades.
2018-08-29 12:30:50 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-29 12:30:50 (DEBUG):    Processing 5 new trades. From 2018-08-29 12:30:32 UTC to 2018-08-29 12:30:34 UTC. (a few seconds)
2018-08-29 12:30:57 (DEBUG):    [ORDER] statusChange: MOVING
2018-08-29T12:30:57.631Z 'bfx cancel'
2018-08-29 12:31:10 (DEBUG):    Requested ETP/USD trade data from Bitfinex ...
2018-08-29 12:31:10 (DEBUG):    No new trades.
...
2018-08-29 15:41:15 (INFO):     Received advice to buy however Gekko is already in the process to sell
2018-08-29 15:41:15 (INFO):     Canceling sell order first
...
2018-08-29 16:36:17 (INFO):     ignoring advice: already in the process to sell
...

sell was executed at 12:30:34, cancel did not get a response. Next advices are ignored.
I've noticed that previous checkOrders were repeated every 2-3 seconds but checkOrders are missing for about 1 minute before statuschange: MOVING
[e12eea0](https://github.com/askmike/gekko/commit/e12eea0279b2c16b2d3e308c09d77e7b24b2d95e) was already merged and did not help.

**Comment by askmike** [comment]
There was a different bug fixed last week regarding order cancels after new
advice. What version of gekko are you running?

**Comment by nervousfinger** [comment]
I'm running hotfix/bfx-sticky with commit from [#2470](https://github.com/askmike/gekko/issues/2470)

**Comment by askmike** [comment]
Anyone experiencing problems with bfx: please run normal develop branch and open a new issue.

**Pull request closed without merging**
