### PR TITLE
Fix #266 bitstamp trader fails to buy

### LINKED ISSUE #240: Unable to buy on bitstamp
(ERROR):	unable to buy: null { error: { __all__: [ 'You need $72.92 to open that order. You have only $72.91 available. Check your account balance for details.' ] } }

Something to with rounding i would guess.

Gekko v0.1.2

I have changed fees and slippage up and down, but no luck. Also looked into portfolioManager.js but i could not figure out where the problem is. Any help appriciated :)

My config is as follows

// Monitor the live market
config.watch = {
  enabled: true,
  exchange: 'Bitstamp', // 'MtGox', 'BTCe', 'Bitstamp', 'cexio' or 'kraken'
  currency: 'USD',
  asset: 'BTC'
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//                       CONFIGURING TRADING ADVICE
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

config.tradingAdvisor = {
  enabled: true,
  method: 'DEMA',
  candleSize: 30,
  historySize: 30
}

// Exponential Moving Averages settings:
config.DEMA = {
  // EMA weight (α)
  // the higher the weight, the more smooth (and delayed) the line
  short: 10,
  long: 21,
  // amount of candles to remember and base initial EMAs on
  // the difference between the EMAs (to act as triggers)
  thresholds: {
    down: -0.025,
    up: 0.025
  }
};

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//                       CONFIGURING PLUGINS
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Want Gekko to perform real trades on buy or sell advice?
// Enabling this will activate trades for the market being
// watched by config.watch
config.trader = {
  enabled: true,
  key: 'my_key',
  secret: 'my_secret',
  username: 'my_username' // your username, only fill in when using bitstamp or cexio
}

config.adviceLogger = {
  enabled: true
}

// do you want Gekko to calculate the profit of its own advice?
config.profitSimulator = {
  enabled: true,
  // report the profit in the currency or the asset?
  reportInCurrency: true,
  // start balance, on what the current balance is compared with
  simulationBalance: {
    // these are in the unit types configured in the watcher.
    asset: 1,
    currency: 100,
  },
  // only want report after a sell? set to `false`.
  verbose: true,
  // how much fee in % does each trade cost?
  fee: 0.5,
  // how much slippage should Gekko assume per trade?
  slippage: 0.05
}

### LINKED ISSUE #266: bitstamp trader fails to buy
apparently bitstamp trader is somehow broken
```
C2015-02-03 02:41:40 (INFO):	Attempting too BUY NaN BTC at Bitstamp
j2015-02-03 02:41:41 (ERROR):	unable to buy: null { error: 'Missing amount and/or price POST parameters' }
```

gekko build from 48fe8b (current master)
`C2015-02-03 02:41:40 (INFO):	Attempting too BUY `
misprint `too BUY`

### PR DESCRIPTION
**Pull request by Siim**
#### Fix #266 
**ticker.ask** had type of **string** and as a result the amount calculation failed. The price should be parsed as **float**.

    amount = this.getBalance(this.currency) / (parseFloat(this.ticker.ask) + (parseFloat(this.ticker.ask)*this.fee));

#### Fix #240 
Fixed floating point to 4 decimal places, because more than 4 places caused inaccurate calculations. 

Btw shouldn't we make all the calculations using cents and satoshis and store all the monetary and asset values in an integer type?

### CODE REVIEW

**Comment by jonny64** [comment]
you have unbalanded  parenthesis

/var/projects/gekko/core/portfolioManager.js:138
eFloat(this.ticker.ask) + (parseFloat(this.ticker.ask)*this.fee))).toFixed(4);
                                                                             ^
SyntaxError: Unexpected token ;

**Comment by Siim** [comment]
Fixed the issues.

**Comment by jonny64** [comment]
looks okay, thanks!

it looks like you have commited someone's key and secret in mocha_test/portfolioManager.js
is this okay? will this test pass every time in future?

>this pull request contains merge conflicts that must be resolved
hm)
you can create separate branch
git fetch && git branch fix_bitstamp 21de73cc292b3a499c32a2f736e52e745eff64af
and recommit needed changes (you can use git checkout --patch to undo whitespace change)

**Comment by Siim** [comment]
Yes it is ok with the key and the test should pass. The key and secret is just for the sake to fill the config fields to make the test work, otherwise the test will fail.

I'll look into the merge conflict.

**Comment by askmike** [comment]
I am assuming this error was specific to Bitstamp's v1 API. As we switched to the v2 API (for buy/sell orders) I think this should not be an issue anymore!

**Comment by askmike** [comment]
actually, I didn't see the tests before. Keeping this open for a little bit..

**Pull request closed without merging**
