### PR TITLE
Binance, fix a case where small purchases could have small rounding errors

### PR DESCRIPTION
**Pull request by cmroche**
This change addresses a case where an attempt to trade the minimal amount may result in small rounding errors which cause the API to reject the order. Ensures that orders are always for the minimum amount.

### CODE REVIEW

**Comment by ms121** [comment]
Ok, it is now throwing the following;

2017-12-06 02:52:27 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: { code: -1105, msg: 'Parameter \'quantity\' was was empty.' }  data: { code: -1105, msg: 'Parameter \'quantity\' was was empty.' }
2017-12-06 02:52:27 (ERROR):	[binance.js] unable to buy { code: -1105, msg: 'Parameter \'quantity\' was was empty.' }

Thanks again!

**Comment by cmroche** [comment]
Typo is fixed

**Comment by ms121** [comment]
@cmroche Seems to be fixed.
Thanks again for the updates!

**Comment by askmike** [comment]
:+1:

**Pull request merged**
