### PR TITLE
[Kraken] Adding back response code 525

### PR DESCRIPTION
**Pull request by cmroche**
This was accidentally dropped in all the kraken work and refactors.

Should address #1439

### CODE REVIEW

**Comment by wakandan** [comment]
does this mean that gekko could not import data from the exchange because the exchange returns error?

**Comment by cmroche** [comment]
@wakandan Yes, hitting this error would have bailed out the import.

**Comment by wakandan** [comment]
does this apply to only kraken or poloniex as well?

**Comment by cmroche** [comment]
Just Kraken

**Comment by askmike** [comment]
:+1:

**Pull request merged**
