### PR TITLE
Broken links in readme

### PR DESCRIPTION
**Pull request by dskvr**
- "Create your own Method Link" is broken.
- One of the "indicators" links was broken.

### CODE REVIEW

**Comment by askmike** [comment]
Thanks! Strategies used to be called "Trading methods", roughly a week ago we changed the name to strategies.

**Comment by askmike** [comment]
Please submit a PR into develop though!

**Comment by dskvr** [comment]
@askmike Will resubmit!

**Comment by askmike** [comment]
thanks :)

**Pull request closed without merging**
