### PR TITLE
Add Bitcoin-co-id exchange

### PR DESCRIPTION
**Pull request by danKHUU**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adding support for Bitcoin.co.id exchange

* **What is the current behavior?** (You can also link to an open issue here)
Not supported. see #1186 

* **What is the new behavior (if this is a feature change)?**
Support for Bitcoin.co.id trading

* **Other information**:

Its working fine so far but longer testing is required iron out bugs. Any tweaks after testing I will commit to this branch.

Keeping it in develop for now.

### CODE REVIEW

**Comment by bitkominer** [comment]
Hi @danKHUU, I've been trying to implement this update into my own branch, but it resulted an error, not able to connect with bitcoin-co-id.

At the initial steps, after "Fetching data...", then shows "Bitcoin-co-id returned an error, retrying..".

Any idea about this error? What should I do to fix it?

**Comment by danKHUU** [comment]
Hi @bitkominer, The only thing i can think of could be your api key or secret is incorrect. 

trying to obtain your account balance.

**Comment by bitkominer** [comment]
OK, it works now. Thanks!

**Comment by askmike** [comment]
Awesome stuff! Would you mind updating the doc page: `/docs/introduction/supported_exchanges`?

**Comment by danKHUU** [comment]
Ok updated :-)

**Comment by askmike** [comment]
:+1: thanks!

**Comment by ariqmuhammadt** [comment]
i always get this error

```
C:\Users\gekko\Desktop\gekko-stable\node_modules\bitcoin-co-id\index.js:65
    requestOptions[x] = options[x];
                   ^

ReferenceError: x is not defined
```

what should i do? i've tried to remove x function but still doesn't work

**Comment by bitkominer** [comment]
@ariqmuhammadt , you should not remove "x". Just go to file index.js inside folder "/node_modules/bitcoin-co-id/", at line#65

`  for (var key in options) {
    requestOptions[x] = options[x];
  }`

Please change it into:
`  for (var x in options) {
    requestOptions[x] = options[x];
  }`

It will resolve your problem.

**Comment by ariqmuhammadt** [comment]
@bitkominer thanks, now it works! it make some trades and profits on the way..

**Comment by bitkominer** [comment]
@ariqmuhammadt, great! 
Would you share the strategy setting you're using which is giving nice profit? Thanks!

**Comment by ariqmuhammadt** [comment]
@bitkominer i use RSI with default setting, 5 minute CandleSize and 10 Period.

**Comment by ariqmuhammadt** [comment]
@bitkominer i found this https://github.com/danKHUU/bitcoin-co-id/commit/7426836e0bd805ebe78f7808881e9e19eebc1fad
should i change "x" to "key"?

**Comment by bitkominer** [comment]
@ariqmuhammadt, yes... you can change that part as revised by danKHUU.

**Pull request merged**
