### PR TITLE
Backtest stats

### PR DESCRIPTION
**Pull request by zappra**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This adds some useful stats to the backtesting summary UI and fixes a few issues

* **What is the current behavior?** (You can also link to an open issue here)

This PR addresses following issues:

#2064 
#2044 
#2002 

* **What is the new behavior (if this is a feature change)?**

New features/fixes are:

Better Sharpe ratio calculation
Correct roundtrip profit and loss calculation
Use complete roundtrips only when calculating final profit
Addition of average/max profit/loss and max drawdown to backtest summary

* **Other information**:

### CODE REVIEW

**Comment by stereohelix** [comment]
Hi zappra,

I'd be interested in contributing to this effort. There are a number of issues I've been thinking about to improve the performance analyzer. Fixing fixing Sharpe ratio seems like a good place to start. I'll comment on [https://github.com/askmike/gekko/issues/2064](url).

**Comment by stereohelix** [comment]
You might also be interested in https://github.com/askmike/gekko/pull/2111, I'm currently using it to optimize multi-pair scalping in gekkoga.

**Comment by askmike** [comment]
Hey! Would you mind PRing this against this branch: https://github.com/askmike/gekko/tree/feature/sync-gekko-events

Which I want to merge into Gekko rather soon.

**Comment by zappra** [comment]
Hi Mike, sure, do I need to create a new PR for that? Or can I edit the current PR - if so, how? Cheers!

**Comment by askmike** [comment]
If you are comfortable with git and rebasing you can do it in this PR, but if not it's probably easier to create just create a new one. Thanks :)

**Comment by stereohelix** [comment]
I added some of my ideas here https://github.com/askmike/gekko/pull/2178 if that's helpful. I'm not particularly good with git but I'd like to coordinate on this.

**Comment by askmike** [comment]
#2178 is merged now. I am closing this. If this PR includes things not in that PR please let me know what :)

**Comment by zappra** [comment]
#2178 fixes the Sharpe ratio, this PR also adds/fixes

Correct roundtrip profit and loss calculation
Use complete roundtrips only when calculating final profit
Addition of average/max profit/loss and max drawdown to backtest summary

**Pull request closed without merging**
