### PR TITLE
Candles patterns

### PR DESCRIPTION
**Pull request by pprados**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add a new indicator "Candles Patterns" to detect some patterns and a new CandlesPatterns strategy.

Detect classical patterns of candles :
- Doji
- DragonflyDoji
- EveningStar
- LongLowerShadow
- LongUpperShadow
- GravestoneDoji
- Hammer
- HangingMan
- HaramiDown
- HaramiUp
- LongLeggedDoji
- Marubozu
- MorningStar
- SpinningTop
- Star

The indicator return a trend.
- `indicator.result` is the trend (>0 go up, <0 go down, 0 unknown)
- `indicator.name` is the name of detected pattern or undefined.
- `indicator.hist[x].pattern.result` is the name of a specific candle in history

To detect a 'doji', 'small' or 'big' the algorithm must calculate the scale
of the currents candles. The parameter `scaleMaxSize` indicate the maximum
last candle to keep in history to calculate the scale.
You can change the coefficient to use.

* **What is the current behavior?** (You can also link to an open issue here)
This indicator MUST be checked more than the units tests can do.

* **What is the new behavior (if this is a feature change)?**

* **Other information**:
Note, this new pattern use the MockGekko proposer in another pull request to check the strategy.

### CODE REVIEW

**Comment by LeMoussel** [comment]
Possible to integrate other patterns like this?
patterns

**Comment by askmike** [comment]
Apologies for the delay, I was on a holiday. Woa! This looks awsome, will test asap.

**Comment by Flippo24** [comment]
I thought this was a base function of TaLib.

[http://ta-lib.org/function.html](http://ta-lib.org/function.html)
Name started with CDL.

**Comment by mathiasrw** [comment]
@askmike Did you review this?

**Comment by Flippo24** [comment]
It is also in src of askmike's fork of talib. So it could be already functional in gekko. 

[https://github.com/askmike/node-talib](https://github.com/askmike/node-talib)

**Comment by JensvdHeydt** [comment]
Any news on this great feature?

**Comment by askmike** [comment]
@pprados apologies for never getting back on this! This is a crazy big PR. Next time this happens please e-mail me directly!

I definetely want to pull in a lot of code, but this is a major change with a lot of changes I don't think are a good idea:

- I don't think unit tests for strategies make sense. The indicators should have unit tests, but not the strategies.
- Where are the numbers in the unit tests coming from? etc

**Comment by pprados** [comment]
I'm sorry, but I haven't the time to continue with this patch.
Someone can continue ? You are wellcome.

**Pull request closed without merging**
