### PR TITLE
Adds Stop runner / watcher button

### PR DESCRIPTION
**Pull request by ricardojsmarques**
Adds a stop button below gekko title.
Internally calls already defined API method `killGekko`.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This change adds a "Stop runner" button in the strat runner and market watcher individual page.

* **What is the current behavior?** (You can also link to an open issue here)
There isn't a way to stop a runner from the UI as shown in #1306 

* **What is the new behavior (if this is a feature change)?**
The added button stops the current live runner (market watcher or strat runner)

* **Other information**:
Currently the button effectively kills the live runner, but I couldn't find a way to update the list view after  the runner was killed. refreshing the page effectively updates the runner lists

### CODE REVIEW

**Comment by osztro** [comment]
@ddrjm ,  I  use 0.5.12 and called the killGekko endpoint from Postman. That may uses the api, but the child process runs after that. So the program keeps running the (watcher|papertrader|tradebot).
Are you aware of this? However you are right, One piece of this puzzle is to make a button available on UI.

**Comment by hilkoc** [comment]
@ddrjm  I've build Gekko with this pull request merged in. It does remove the runners from the UI. However it does not kill the process! Like @osztro says, Gekko keeps executing trades/fetching data after clicking the stop button.

@askmike How do we correctly kill the child process?

**Comment by osztro** [comment]
@hilkoc node package https://www.npmjs.com/package/tree-kill
use that to stop the gekko process
store the PID (process id ) of the gekko in the gekkoManager (the cache) and listManager. currently a randomly generated id is the key in the cache (gekkoManager)
use the existing killGekko.js as an entry point to perform the stop of the process.

**Comment by askmike** [comment]
@osztro the child process currently doesn't handle graceful shutdown very well, there is some more work involved than simply killing the process to make sure we clean up DB handlers and the such.

This (most desired) functionality is planned for in the next UI release, I already have a rewritten all code that manages running gekkos (current code was alpha & spaghetti code) will push this to #1850 asap. Better to hook proper lifecycle management in there.

Apologies to @ddrjm for putting the time in to write this, but I think the best thing would be to close this for now.

**Comment by hilkoc** [comment]
Thanks @ddrjm , with the help of this button in the UI I managed to make a working stop button. See my last comment on #2059.

**Pull request closed without merging**
