### PR TITLE
Support configurable order update delays

### LINKED ISSUE #1714: Binance Error
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tried to run using @cmroche branch product_updates using candle sizes from 1-5 mins.

* **Expected result** (what you hoped would happen)
buys to go through (keeps canceling and retrying after about 50s

* **Actual result** (unexpected outcome)
2018-01-18 01:31:52 (INFO):     BUY order was not (fully) filled, cancelling and creating new order
2018-01-18 01:31:52 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400
2018-01-18 01:32:03 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400
2018-01-18 01:32:16 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400
2018-01-18 01:32:30 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400
2018-01-18 01:32:48 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400
2018-01-18 01:33:10 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400
2018-01-18 01:33:35 (DEBUG):    [binance.js] (cancelOrder) returned an error, retrying: Error: Response code 400

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

It seems to be unable to fill orders and will cancel them too soon. Maybe set the price slightly lower at which it buys? I'm not quite sure how to fix but if I was able to use 1min candle sizes on binance that'd be great. If you can fix this email me: falatime@gmail.com with an ethereum address. Thanks!!

### PR DESCRIPTION
**Pull request by cmroche**
Simple config change to slow down the update rate of unfilled orders. Should resolve #1714

### CODE REVIEW

**Comment by ghost** [comment]
Needs check for conf.orderUpdateDelay if using UI version it will throw an undefined error.

**Comment by askmike** [comment]
Agreed with @mvanbosc!

**Comment by cmroche** [comment]
@mvanbosc @askmike You mean it needs a check for `conf`? The way the code is written right now is that it shoudl fall back to 1 minute of the field isn't specified... or am I missing something?

So this is what you want?

`let cancelDelay = (conf && conf.orderUpdateDelay) || 1;`

**Comment by ghost** [comment]
@cmroche I just deleted the line conf.orderUpdateDelay because if you run from web version it'll crash saying it can't find conf.orderUpdateDelay. So to answer your question - yes.

**Comment by cmroche** [comment]
@mvanbosc Can you give me a call stack for the crash please? I am unable to cause a crash on my side, so there must be an action I am not testing.

**Comment by cmroche** [comment]
Bah.. I just figured it out, silly mistake. Was missing the `this`

**Comment by askmike** [comment]
Ah that was it. It would be good to keep the baseConfig as much in sync with the sample-config allowing people to overwrite default values more easily. But I'll do that myself now :)

**Pull request merged**
