### PR TITLE
Docker: further improve

### PR DESCRIPTION
**Pull request by DeviaVir**
@askmike as promised in:
https://github.com/askmike/gekko/pull/743#issuecomment-301745225

Now also updated the `README` on how to jump in.

### CODE REVIEW

**Comment by DeviaVir** [comment]
Cool detail: you can switch port and domain basically on the fly without rebuilding the image.

```
HOST=test.com PORT=3001 docker-compose up -d
HOST=test2.com PORT=3002 docker-compose up -d
```

does the switch

**Comment by askmike** [comment]
woow this is great stuff! Thanks a lot :)

One question: installation details used to live in the main `README.md` but have now moved to this folder: https://github.com/askmike/gekko/tree/stable/docs/installation

Would you mind moving that information into `installing_gekko_using_docker.md`? Those files are used to generate the documentation website and (once I [rebuild docs](https://github.com/askmike/gekko.wizb.it#readme)) it will be reflected here:

https://gekko.wizb.it/docs/installation/installing_gekko_using_docker.html

**Comment by DeviaVir** [comment]
@askmike sure, updated!

**Comment by askmike** [comment]
thanks :) I merged it.

I did rewrite the docs (to explain that you don't need to bother with host/port if you want to run it on you own computer - you only need those when running externally).

https://gekko.wizb.it/docs/installation/installing_gekko_using_docker.html

**Comment by oscarteg** [comment]
How do you secure Gekko with username/password using this file?

**Comment by askmike** [comment]
@Oscarteg I am not sure what you mean, please open a new issue.

**Comment by DeviaVir** [comment]
@Oscarteg this is why I included a commented out nginx proxy:
https://github.com/askmike/gekko/blob/stable/docker-compose.yml#L26

Please see their docs on basic auth to find the answer to your question:
https://github.com/jwilder/nginx-proxy#basic-authentication-support

**Pull request merged**
