### PR TITLE
Pushbullet Plugin update round 2

### PR DESCRIPTION
**Pull request by GryphonR**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Further feature Improvement to pushbullet plugin, as discussed in #2549 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
* Doesn't send irrelevant information when paper trading is enabled
* Gives Round trip and total profit loss in currency and percentage
* Includes cost of trade as passed in from onTradeCompleted event
* Gives exposure time in a humanized string
* Clarified 'Slip' to 'Slip from advice price' - only shown in live trading

Behavior for Paper Trading: 
image

Running it on a live bot now for testing - will update once I have the output.

* **Other information**:

### CODE REVIEW

**Comment by GryphonR** [comment]
Live test screenshot: 
image

Needs couple of tweaks to formatting, and I think I'll add the round trip PL% to the subject line so that it's visible in the notification. Most important info after all!

**Comment by GryphonR** [comment]
Incidentally, the cost of trade that's reported by gekko seem to be a few orders of magnitude lower than the 0.1% fee I expect on Binance.

**Comment by askmike** [comment]
> Incidentally, the cost of trade that's reported by gekko seem to be a few orders of magnitude lower than the 0.1% fee I expect on Binance.

A bug fix was recently fixed! Gekko didn't assume the correct fee on binance. Can you make sure this PR is merged in your local version? #2578. Not quite sure if that's the result of what you are seeing, but it's good to have that anyway.

**Comment by GryphonR** [comment]
> Can you make sure this PR is merged in your local version? #2578.

Thanks, but I'd pulled develop before testing and submitting the PR. Just checked and I definitely have PR #2578 locally already

I've just calculated it manually... Trade amount was 0.01645438 BTC, Gekko reported cost was 0.00001645 BTC  - which actually works out at the expected 0.1%. Looks like the mistake is in my code, not gekko's, sorry! I'll get it patched.

**Comment by GryphonR** [comment]
Fixed. I had missed that the trade.amount was in Asset and trade.cost was in Currency. Multiplied amount by price and tests show expected costs.

Latest output:
image

**Comment by askmike** [comment]
great stuff! I'll test it out now and will merge if I don't run into problems.

**Comment by askmike** [comment]
Apologies for the late merge!

**Pull request merged**
