### PR TITLE
Buzzex Exchange

### PR DESCRIPTION
**Pull request by mrcrislainez**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added new exchange: Buzzex

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by askmike** [comment]
Great stuff!

Could you add `buzzex-gekko-npm` as a dependency in package.json? Also would you happen to know where that code is stored under git? The package.json refers to `https://github.com/ipabz/buzzex-gekko-npm` but that repo does not seem to exist.

**Comment by mrcrislainez** [comment]
> https://github.com/ipabz/buzzex-gekko-npm



> Great stuff!
> 
> Could you add `buzzex-gekko-npm` as a dependency in package.json? Also would you happen to know where that code is stored under git? The package.json refers to `https://github.com/ipabz/buzzex-gekko-npm` but that repo does not seem to exist.

Does the repo needs to be public? Coz it's in private right now.

**Comment by askmike** [comment]
I looked at the code from the NPM package just now (v `1.0.0`). If you pin the version used by Gekko to 1.0.0 that's technically sufficient (but not ideal).

**Comment by mrcrislainez** [comment]
Im closing this PR. Ill make another PR.

**Pull request closed without merging**
