### PR TITLE
Updated binance market data using script provided in PR #1550 by @cmroche

### PR DESCRIPTION
**Pull request by mronus**
Fix for #1678

Updated binance market data using the script provided in PR #1550 by @cmroche

### CODE REVIEW

**Review by cmroche — APPROVED** [review]

**Comment by askmike** [comment]
:+1: thanks :)

**Comment by nissimpradhan** [comment]
Can binance market data using the script be done automatically when using import option form the Gekko UI? I think that would be great. If it hasn't been done, l'd love to do it myself.

**Comment by askmike** [comment]
No, you have to manually run the update file.

The reason we do it like this is so that we can make sure Gekko only works with markets that we have tested and seen. We could also dynamically look up markets whenever you start Gekko, but that defeats the purpose.

**Comment by nissimpradhan** [comment]
What do you mean by tested and seen? Binance keeps adding new coins to the exchange, Gekko should support those trading pairs isn't it? I thought that was the purpose of the script.

It's not a ideal to run it every time we use the importer but perhaps, a "sync currency pairs" button in the import page definitely helps.

**Comment by askmike** [comment]
The problem is that there are differences in how they report their markets
and how they actually are. We are not handling it yet but we will, see
https://github.com/askmike/gekko/pull/1805

**Comment by askmike** [comment]
And honestly using gekko on brand new coins does not make sense. Gekko is
for trendwatching and momentum reversal. You can't do that on brand new
markets imo.

**Comment by jbghub** [comment]
I am new to Gekko. This discussion is very confusing. I would like to see more coins available in Gekko for trading listed by Bianance. If an update has been prepared that will accomplish this I would like to know how to install the update. Thanks

**Comment by stereohelix** [comment]
jbghub, here's a way to update for more coins without having to use any other tools:

-Make a backup copy of gekko/exchanges/binance.js
-Then open your current file, copy the contents of this into it, and save:
https://github.com/askmike/gekko/blob/c3de6f653930b1a8a58ef5071cfd0537664dc7d3/exchanges/binance.js

**Comment by jbghub** [comment]
Thank you so much. I will implement later this evening.

**Comment by jbghub** [comment]
I updated the binance.js file as stated. However, I am still only seeing the same 5 coins in the Gekko app. Any suggestions?

**Comment by stereohelix** [comment]
Stop and restart gekko?

**Comment by jbghub** [comment]
Yes, Stopped, Restarted Gekko; also rebooted PC. Any other ideas?

**Comment by jbghub** [comment]
I am using the Admin Command window to start Gekko:
node gekko --ui
then going to http://localhost:3000/#/home in Chrome browzer.

**Comment by stereohelix** [comment]
Hi jbghub,
Sorry, now I'm confused about this. I don't know how you could only show five coins after restarting, since the binance.js file is the only file where that information is read from. This might be beyond my ability to hack. Are you sure you edited the correct file? The only other thing I could suggest is restoring the files, pulling gecko again fresh (using git pull) and then trying again.

Good luck, hope that helps.

**Comment by jbghub** [comment]
I found this code in the package-lock file:
"binance": {      "version": "1.3.1",      "resolved": "https://registry.npmjs.org/binance/-/binance-1.3.1.tgz"

Could this have anything to do with the binance file not working for me?

**Comment by stereohelix** [comment]
I'm not sure. But that is a little out-of-date.

You could try 
npm uninstall binance
npm install binance

But I should really add a disclaimor that I'm in over my head here -- if this causes some other conflict, you might end up having to reinstall gekko. Which might be fine, and might actually solve whatever issue is happening.

**Comment by jbghub** [comment]
I believe I found my problem. I was only looking at the USDT pairs. Their are many more coins for other currencies (coins) instead of USDT.

**Comment by jbghub** [comment]
Thanks for all your help.

**Comment by stereohelix** [comment]
Great!

**Comment by jbghub** [comment]
Quesion: How did you determine the Precision of each coin?

**Comment by stereohelix** [comment]
The easiest way is to look on the Binance website. The precision is the least significance digit of the price.

**Comment by cmroche** [comment]
@stereohelix @jbghub Right now it happens to be the least significant digit of each coin, but Binance does publish somewhere in their documents and official list, and it is queryable through their API for official values as there is no guarantee of this relationship in the future.

**Comment by stereohelix** [comment]
Here's the official document (it's actually pretty up-to-date, not 8 months old)
https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

**Pull request merged**
