### PR TITLE
Commands and remote logging

### PR DESCRIPTION
**Pull request by zappra**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This adds two new features: command events and remote logging

* **What is the current behavior?** (You can also link to an open issue here)

Plugins like the telegram bot offer a window to communicate with Gekko but with limited utility.

* **What is the new behavior (if this is a feature change)?**

This PR adds a new 'command' event type to allow telegram (or other similar plugins) to emit commands to other plugins, the core trading logic and the currently running strategy.

This opens up a bunch of opportunities, like manual buys/sells, querying internal strategy state, setting strategy parameters on the fly, etc

This PR also adds a new 'remote' log channel. Plugins can register themselves as a remote logger, which will then receive any messages sent with log.remote. This allows two way comms with command emitting modules and eg. the running strategy.

An example strategy is included that simply responds to 'help', 'buy' and 'sell' commands.

* **Other information**:

Not sure how easy this is to merge against recent changes to the core trading logic!

This PR changes telegrambot to use tgfancy which includes, amongst other things, guaranteed ordering of submitted messages

### CODE REVIEW

**Comment by askmike** [comment]
Apologies for the extremely late reply. Have you seen #1850? I think there is a lot of overlapping func.

**Comment by zappra** [comment]
It's quite a simple change really, just adding a new event type that can be emitted by bot-type plugins (telegram, IRC, etc) Wasn't sure how well it would merge with the new code.

The remote logging feels like a bit of a hack tbh, wasn't sure of the best way to implement. However being able to emit commands to Gekko is pretty useless unless there's a way for Gekko to respond!

This functionality is super useful in my current setup but understand if there's overlaps with other PR's

**Comment by whoodat** [comment]
Hi Zappra, I downloaded your clone and wanted to try your telegram out and tried to run gekko and am receiving the following error with the telegrambot.
2018-05-28 13:54:15 (DEBUG):	Scanning backwards...2018-05-28T18:38:06.879Z
Unhandled rejection Error: 404 {"ok":false,"error_code":404,"description":"Not Found"}
    at /home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/lib/telegramPolling.js:133:17
    at tryCatcher (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by zappra** [comment]
@whoodat Hi Sorry for late reply, I haven't seen that error before, have you installed tgfancy?

As for commands supported, it's up to your strategy how you implement them. All the bot does is tokenise command and argument strings.

Due to real world commitments haven't got a lot of time to work on Gekko atm... hope this helps

**Comment by whoodat** [comment]
@zappra I installed the npm tgfancy and I am sitll getting the same error. It seems to get very upset with the telegrambot for w/e reason:

Unhandled rejection Error: 404 {"ok":false,"error_code":404,"description":"Not Found"}
    at /home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/lib/telegramPolling.js:133:17
    at tryCatcher (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/whoodat/Gekko/gekko-zappra/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Pull request closed without merging**
