### PR TITLE
Include STDDEV in tulind.js

### LINKED ISSUE #2469: Gekko does not support tulips' standard deviation
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

I can't find the tulip standard deviation indicator in Gekko's tulind.js, although according to the tulip site (https://tulipindicators.org/stddev) it's one of the indicators. Am I missing something, or is tulind.js missing the indicator? Thanks for your help!

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

### PR DESCRIPTION
**Pull request by H256**
add missing stddev

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
added tulip.stddev to available indicators.

* **What is the current behavior?** (You can also link to an open issue here)
stddev is missing in the list.

* **What is the new behavior (if this is a feature change)?**
stddev is being calculated in custom strategies

* **Other information**:
should fix https://github.com/askmike/gekko/issues/2469

### CODE REVIEW

**Comment by askmike** [comment]
:+1:

**Comment by askmike** [comment]
Did you test it by any chance?

**Comment by H256** [comment]
I've quickly mocked up a test-strategy -> there's results coming in, so i guess: it works. ;)
grafik

**Comment by askmike** [comment]
awesome, thanks!

**Pull request merged**
