### PR TITLE
[DOCS] about_gekko.md: add consistent information for the risk of someone having access to your gekko

### PR DESCRIPTION
**Pull request by bmarchesini**
Add consistent information for the risk of someone having access to your gekko by establishing what can happen.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update

* **What is the current behavior?** (You can also link to an open issue here)
None information about this subject

* **What is the new behavior (if this is a feature change)?**
Add consistent information for the risk of someone having access to your gekko by establishing what can happen.

* **Other information**:

### CODE REVIEW

**Comment by askmike** [comment]
I like this disclaimer, but the general about me isn't the right place. Because while the issuers are valid at that point people reading this have no idea what "someone having access to your gekko" means.

**Comment by bmarchesini** [comment]
Can I put this in "Getting help"? It may seem like a better place to me

**Comment by askmike** [comment]
I don't think that's a place people would go to when they go looking for this information. A better way would be to create a new document under installation that first discusses those risks and than talks about how you can prevent people from "having access to your gekko" (which depends on if you run Gekko on your own computer, or server, etc).

We can then link to this document in the installation guides (a place good place where people need to be reminded of these kind of risks).

What do you think of that?

**Comment by bmarchesini** [comment]
We could call this section "Possible Risk" and in this document I would put the content of this PR and add a TODO for the prevention part until I write it. How are the docs folders and files processed to add them?

**Comment by bmarchesini** [comment]
Up

**Comment by askmike** [comment]
When it comes to automated trading "risk" always refers to your money at risk (measured one way or another). What about something like "Security" or "Security risk"?

**Comment by bmarchesini** [comment]
Yes it seems to me a good idea, apart from creating the folder and.md file for the doc, is there another file to modify to refer this file and that it appears in the right place in the doc?

**Comment by askmike** [comment]
You can simply create one new document inside the installation folder here: https://github.com/askmike/gekko/tree/develop/docs/installation

I think the installation files should be sufficient :)

**Comment by askmike** [comment]
Will be superseded by #2672.

**Pull request closed without merging**
