### PR TITLE
Better slack messages

### PR DESCRIPTION
**Pull request by tg44**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
PIMP the slack messages for a more readable format.

* **What is the current behavior?** (You can also link to an open issue here)
screen shot 2017-12-26 at 11 24 26

* **What is the new behavior (if this is a feature change)?**
screen shot 2017-12-26 at 11 24 45

* **Other information**:
Just see the pictures :D

### CODE REVIEW

**Review by greenbigfrog — APPROVED** [review]

**Comment by herkyl** [comment]
Usage of template strings would make this code much easier to read. Nice PR though, so much more readable!

**Comment by tg44** [comment]
@herkyl like this?

**Comment by herkyl** [comment]
I was referring to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals . This change really good as well.

**Comment by tg44** [comment]
I would let that go for now. I'm not qualified enough to make this change without braking the code. Plus I think that wouldn't make it more readable... I could use that in 3 places. L42 is problematic bcs of the backticks in the string. L83 has more code than string. L88 is an url  (`/asd/${asd}.png`). I wouldn't use string literals in these cases in scala either :D

**Review by herkyl — APPROVED** [review]

**Comment by askmike** [comment]
looks great, thanks!

**Pull request merged**
