### PR TITLE
Add OMG, ZRX, CVC, GAS assets to BTC and ETC currencies

### PR DESCRIPTION
**Pull request by xFFFFF**
should be script to auto updates like for binance

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
pairs update

* **What is the current behavior?** (You can also link to an open issue here)
havent gas, cvc, omg,zrx pairs

* **What is the new behavior (if this is a feature change)?**
have pairs :D

* **Other information**:
havent, but I added and now have :)

### CODE REVIEW

**Comment by VeeeneX** [comment]
It would be better if it could be automated

**Comment by xFFFFF** [comment]
Its true. But I haven't skills to write script in javascript to auto update.

GNO is missed too but only in array: assets. How I can edit file from this PR?

**Comment by askmike** [comment]
thanks!

**Comment by askmike** [comment]
@VeeeneX yes it would be, this is automated for a number of exchanges such as bitfinex and binance. Very open to PRs to extend this to polo :)

**Pull request merged**
