### PR TITLE
[DOC] adding strategy example and candle description

### PR DESCRIPTION
**Pull request by raffus**
Added new strategy example to help users to build their own strategies.
I've also added the candle variables so users can better understand the available options when writing their own strategies.

### CODE REVIEW

**Comment by askmike** [comment]
Great stuff! Great idea and I'll go over the text specifically soon :)

**Comment by askmike** [comment]
I just updated the develop branch, would you be able to rebase this PR branch? If not let me know and I can create a new PR that includes your commits.

**Comment by askmike** [comment]
ping @raffus, see previous comment.

**Comment by raffus** [comment]
Hi @askmike. I thought you were asking me to do it in my fork and then do another PR, which I did recently.

Rebase is beyond my skills at this time, I could do a research but if you don't mind to do it, I'd be glad. Teaching me how to do it also would be nice. ;)

**Comment by askmike** [comment]
Not quite sure when these commits got merged, but they did!

- see https://github.com/askmike/gekko/commit/6a08266dfc2f8acc1a39621e14e3428afd2b96ab#diff-9ebbec6bbdb955bee984da33b61b5c9e
- see https://github.com/askmike/gekko/commit/4273758e7c89df7737cbb5884e3e7ad39a4c3deb#diff-9ebbec6bbdb955bee984da33b61b5c9e

**Comment by raffus** [comment]
So, did it work? Do I still have to do it again? lol

**Comment by askmike** [comment]
No you are fine! If you click the two commit links you can see that your commits were added to Gekko. Here you can see it as well: https://github.com/askmike/gekko/blob/stable/docs/strategies/creating_a_strategy.md#basic-strategy-example

**Pull request closed without merging**
