### PR TITLE
Fix Bitstamp BTC buy units, and add BCH asset

### PR DESCRIPTION
**Pull request by kevinmershon**
- [x] Bitstamp now allows trading with Bitcoin Cash (BCH)
- [x] Bitstamp minimum buy order is now 0.001 BTC for BTC-denominated currency pairs

### CODE REVIEW

**Comment by askmike** [comment]
great, thanks :)

**Comment by greenbigfrog** [comment]
@kevinmershon not sure if it's just github bugging out, but you don't seam to be basing you're PRs off of askmike's clean develop branch, and hence making the `Files Changed` quite hard to read. Mind basing your PRs off of the remote develop branch?

**Comment by askmike** [comment]
@greenbigfrog I changed the target branch, it was originally aimed at master. Though this meant that there were now more diffs (since the master does not have things the latest develop has).

Better would be to ask people to rebase their branches on latest develop if they opened the PR against master. But in this case I thought it was a bit much, since I can squash rebase whilst merging (making gekko's git log clean, but this one not so clean).

You can see the changes of this PR here: https://github.com/askmike/gekko/pull/1477/commits/8da24e0555e50db28400546bfd83c67aea89e7e8

EDIT: I am actually thinking of making develop the default branch, and point the download docs to the [releases](https://github.com/askmike/gekko/releases) (so most people just download a stable release). If I do that this problem goes away since all PRs will automatically open against develop.

**Comment by greenbigfrog** [comment]
@kevinmershon @askmike sorry. missed the line of you changing target branch... https://dogecoin.is-going-to.space/8e2679.png

But I second changing the default branch to develop.

**Pull request merged**
