### PR TITLE
Fix loading JPG file on non standard install

### PR DESCRIPTION
**Pull request by JReming85**
This will load the image file reguardless of the path set in web/vue/UIconfig.js as it will always look for assets in the same directory as you browsed to

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

Currently the jpg on the main page is set to staticly pull from /asset/gekko.jpg

* **What is the new behavior (if this is a feature change)?**

This will dynamically set the the root folder to match the set path

* **Other information**:

### CODE REVIEW

**Comment by askmike** [comment]
You've only pushed an update to the compiled build file. This would get overwritten whenever we update something in the frontend app and recompile. Could you pushed the change to whatever source files you changed (inside this dir `gekko/web/vue/src`)?

**Comment by greenbigfrog** [comment]
@askmike mind diversifying your labels a bit? In this case you aren't really waiting on an answer, but on a update.

**Comment by JReming85** [comment]
@askmike Hey sorry about that, submitting it now

**Comment by JReming85** [comment]
#1498

**Comment by askmike** [comment]
#1498 has been merged!

**Pull request closed without merging**
