### PR TITLE
Fix Binance ICX/BNB minial order amount is 1

### PR DESCRIPTION
**Pull request by namns1412**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix Binance ICX/BNB minial order amount is 1

* **What is the current behavior?** (You can also link to an open issue here)
Current amount is 0.01

* **What is the new behavior (if this is a feature change)?**
Current amount is 1

* **Other information**:
Fix strat stop when try to sell under 1 ICX

### CODE REVIEW

**Comment by askmike** [comment]
@namns1412 you might be correct, but that JSON is generated by this file:

https://github.com/askmike/gekko/blob/develop/util/genMarketFiles/update-binance.js

Which we run occasionally to add new market support to Gekko. That file gets it's data from Binance itself ([see this link](https://www.binance.com/exchange/public/product)). So approving this PR wouldn't fix things for long. Would you mind also adding some the correction here as well:

https://github.com/askmike/gekko/blob/develop/util/genMarketFiles/update-binance.js#L42

so that we can apply that fix everytime we generate market files?

cc @cmroche.

**Comment by cmroche** [comment]
@askmike @namns1412 Try regenerating the product list first to make sure the markets were not updated by their API. Last time I saw a descrepency like this it required it was due to an update.

If that doesn't fix the issue, then do as askmike suggested and put an exception in the update script.

**Comment by n3us3ns3** [comment]
<iframe width="854" height="480" src="https://www.youtube.com/embed/3l2_KpfCcmA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

**Comment by cmroche** [comment]
I reported the above post from @n3us3ns3 as spam, would you please remove it @askmike

**Pull request closed without merging**
