### PR TITLE
Fix to importer dates

### PR DESCRIPTION
**Pull request by rkingy**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Fix date issues in importer.
https://github.com/askmike/gekko/issues/2563#issuecomment-425038916 

* **What is the current behavior?** (You can also link to an open issue here)

Dates from the GUI are wrong.. 

* **What is the new behavior (if this is a feature change)?**

Everything works as expected again in UTC format.

* **Other information**:

### CODE REVIEW

**Comment by mark-sch** [comment]
It is some time ago, but I remember similar import issues when dealing with PostgreSQL db. To get it working there had been some moment and utc changes necessary. Which db are you using? Maybe it needs deeper testing with different db environments...

**Comment by rkingy** [comment]
Hi @mark-sch  I'm just using the standard install. I believe it uses "sqlite3": "^4.0.0",
This has only been an issue I've noticed since upgrading a fresh install to the latest 0.6.6 version. I had been using the older version for quite a long time.

Your probably right if people are using different dbs that handle dates differently. But for those that clone the repo and run for the first time it also needs to work out of the box.

Without the .utc treatment this is what the GUI looks like when doing a import. Starts off in negative % bar and then never imports up to the date you want.

screenshot 2018-09-29 11 43 37
screenshot 2018-09-29 11 43 42

**Comment by askmike** [comment]
@rkingy @mark-sch thanks for providing a fix and context. I will test this with both sqlite and postgres asap.

**Comment by askmike** [comment]
this PR fixes the importer using both databases for me. I am currently in UTC+8 and I definitely noticed the offset, I think always. With this PR the problem goes away for me.

@mark-sch if you encounter problems after this PR please let me know!

**Pull request merged**
