### PR TITLE
Hotfix/gb kraken

### LINKED ISSUE #2286: Kraken: "This exchange is not yet supported"
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I run Gekko since 6 months and it worked fine with Binance and Kraken.
I wanted to use new pairs available on Binance, so I updated Gekko from the repository (develop).
I had several issue (not compatible with my NodeJS version, ...) but I succeded to make it work.

But when I use my existing strategy on Kraken, it says:
"
Gekko encountered an error and can't continue
Error:
This exchange is not yet supported
"

I tried to install, delete, reinstall "kraken-api", "kraken-api-es5", run "update-kraken.js", ... nothing works.

Note : if I don't enable the live trade, it works.

**Expected result** (what you hoped would happen)
Be able to trade on Kraken.

**Actual result** (unexpected outcome)
Can't trade on Kraken.

Gekko version: v0.6.1
Nodejs version: v8.11.3

### PR DESCRIPTION
**Pull request by askmike**
fixes #2286.

### CODE REVIEW

**Comment by skylinetech-team** [comment]
hi, I tried Gekko v0.6.8 and Gekko UI v0.2.3.

still seeing this issue

just start trade bot with 

exchange: Kraken
currency: GBP
Asset: ETH

you'll see the following errors:

2019-12-11T21:26:37.617Z 'Cannot read property \'XETH\' of undefined'
TypeError: Cannot read property 'XETH' of undefined
    at handle (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/wrappers/kraken.js:223:46)
    at checkFn (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/exchangeUtils.js:24:16)
    at /home/markhu/skyline_prod/client00001/gekko-4000/exchange/wrappers/kraken.js:177:12
    at response.then (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/node_modules/kraken-api/kraken.js:173:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
unhandledRejection { Error
    at Object.<anonymous> (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/exchangeErrors.js:9:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/exchangeChecker.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
  name: 'ExchangeError',
  message:
   TypeError: Cannot read property 'XETH' of undefined
       at handle (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/wrappers/kraken.js:223:46)
       at checkFn (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/exchangeUtils.js:24:16)
       at /home/markhu/skyline_prod/client00001/gekko-4000/exchange/wrappers/kraken.js:177:12
       at response.then (/home/markhu/skyline_prod/client00001/gekko-4000/exchange/node_modules/kraken-api/kraken.js:173:23)
       at process._tickCallback (internal/process/next_tick.js:68:7) }

**Comment by skylinetech-team** [comment]
any advises ?

**Comment by skylinetech-team** [comment]
tried clean install gekko, still seeing the same error

**Comment by skylinetech-team** [comment]
2019-12-11T21:40:03.266Z 'Cannot read property \'XETH\' of undefined'
TypeError: Cannot read property 'XETH' of undefined
    at handle (/home/markhu/skyline_prod/client00001/gekko4000/exchange/wrappers/kraken.js:223:46)
    at checkFn (/home/markhu/skyline_prod/client00001/gekko4000/exchange/exchangeUtils.js:24:16)
    at /home/markhu/skyline_prod/client00001/gekko4000/exchange/wrappers/kraken.js:177:12
    at response.then (/home/markhu/skyline_prod/client00001/gekko4000/exchange/node_modules/kraken-api/kraken.js:173:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
unhandledRejection { Error
    at Object.<anonymous> (/home/markhu/skyline_prod/client00001/gekko4000/exchange/exchangeErrors.js:9:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/markhu/skyline_prod/client00001/gekko4000/exchange/exchangeChecker.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
  name: 'ExchangeError',
  message:
   TypeError: Cannot read property 'XETH' of undefined
       at handle (/home/markhu/skyline_prod/client00001/gekko4000/exchange/wrappers/kraken.js:223:46)
       at checkFn (/home/markhu/skyline_prod/client00001/gekko4000/exchange/exchangeUtils.js:24:16)
       at /home/markhu/skyline_prod/client00001/gekko4000/exchange/wrappers/kraken.js:177:12
       at response.then (/home/markhu/skyline_prod/client00001/gekko4000/exchange/node_modules/kraken-api/kraken.js:173:23)
       at process._tickCallback (internal/process/next_tick.js:68:7) }

**Comment by skylinetech-team** [comment]
did anyone see this kraken tradebot error with latest Gekko ?

thanks

**Comment by skylinetech-team** [comment]
paper trade is fine

just trade bot showing erorr - not working with kraken

**Comment by sanitariu** [comment]
This project is dead. Go for freqtrade or zenbot. Anyway they work better for sure.
Gekko was working good too but is abondened from 1 year for going to be paid one.....

**Comment by skylinetech-team** [comment]
seems Mike said - this project is not abandoned @askmike Mike ?

**Pull request merged**
