### PR TITLE
updated the readme

### PR DESCRIPTION
**Pull request by obiknows**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by obiknows** [comment]
cool

**Comment by askmike** [comment]
:-1:

**Comment by obiknows** [comment]
oh shit, my bad i thought this was on my fork only

**Comment by askmike** [comment]
Ah! No worries, but I couldn't merge this in unfortunately ;)

**Pull request closed without merging**
