### PR TITLE
Cleanup QuadrigaCX market top level declarations

### PR DESCRIPTION
**Pull request by jcoder76**
- Changed the top level declarations to use const instead of var
- Reordered top level declarations to match other exchanges

### CODE REVIEW

**Comment by jcoder76** [comment]
@cmroche this is the first part of the changes for the Quadriga market.

**Comment by jcoder76** [comment]
@cmroche not sure whether you want to pull this or not, but it does improve the headers in the quadriga.js market file and makes them consistent with the other markets.

**Comment by askmike** [comment]
I'm all up for these changes, but the branches are currently conflicting. Would you mind rebasing or creating a new branch from an up to date askmike/gekko:develop branch and commiting this on top again?

**Comment by askmike** [comment]
It might have had to do with me merging another PR that also fixed some codes in QuadrigaCX. Apologies for the delay in responding to PRs.

**Comment by askmike** [comment]
I am since focussing all my efforts in the 0.6 release. Please make sure all PRs point to this branch (until it is merged): #2216

**Comment by askmike** [comment]
Closing this due to inactivity :( Feel free to comment

**Comment by jcoder76** [comment]
SorryI'm being slow on these changes.  I'll fix it up and resubmit later.

**Comment by askmike** [comment]
@daflame76 can't wait!

Note though that Gekko has since undergone some major upgrades, if we want to support QuadrigaCX again we need to do more changes:

- Everything is now inside GB (Gekko Broker - path: `exchange/wrappers`)
- Wrappers cannot import code from outside GB like the gekko logger and such: GB is also a standalone library
- cancelOrder has changed (the objects passed to the callback)
- checkOrder has changed  (the objects passed to the callback)
- A few new methods are now required (like `roundPrice`, `roundAmount`, etc)
- capabilities has some new fields, like gekko broker version.
- error handling is different now.

See the add an exchange doc for details on above.

I'm swamped with work, so I won't be able to do this anytime soon :(

**Comment by jcoder76** [comment]
Thanks for the heads up.  Looking forward to all the improvements.

**Pull request closed without merging**
