### PR TITLE
Fix deprecated call to moment

### PR DESCRIPTION
**Pull request by cmroche**
Very simple change, fixing a deprecated call to moment().subtract

### CODE REVIEW

**Review by greenbigfrog — APPROVED** [review]

**Review by keustma — APPROVED** [review]

**Comment by woehrer12** [comment]
I tested it.
The problem is not fixes with this change

**Comment by greenbigfrog** [comment]
What "problem"? @woehrer12

**Comment by woehrer12** [comment]
2017-12-18 22:45:48 (DEBUG):	Processing 2597 new trades. From 2017-12-18 21:07:08 UTC to 2017-12-18 21:45:45 UTC. (39 minutes)
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_MISUSE: Database is closed
    at Error (native)
    at Database.<anonymous>

**Comment by cmroche** [comment]
@woehrer12 Your warning is about a misused .add, this one fixes a misused .subtract. If you can find out where it is being incorrectly used please open a new issue and it will be fixed.

**Pull request merged**
