### PR TITLE
Switch to telegram command style

### LINKED ISSUE #1297: Telegram bot commands missing / prefix
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Sending commands to Telegram bot starting with a / like "/advice"

* **Expected result** (what you hoped would happen)
A response message with the advice.

* **Actual result** (unexpected outcome)
A message containing "Hello!". This is the default response when a command isn't regonized.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
The commands defined for the Telegram bot are missing the leading / . By convention Telegram bot commands start with a / .
Following this convention makes it possible to define a list of commands via Telegram BotFather. This command list results in an extra button to easily select a command instead of typing it every time.

Simple fix would be adding / to the commands in plugins/telegrambot.js like this:
```javascript
this.commands = {
  '/advice': 'emitAdvice',
  '/price': 'emitPrice',
  '/donate': 'emitDonation',
  '/real advice': 'emitRealAdvice',
  '/help': 'emitHelp'
};
```

### PR DESCRIPTION
**Pull request by greenbigfrog**
Normally commands for Bots on Telegram start with a `/`: https://core.telegram.org/bots#commands

Closes #1297

### CODE REVIEW

**Comment by askmike** [comment]
:+1:

**Comment by greenbigfrog** [comment]
Might be a good idea to mention this change in the release notes

**Comment by askmike** [comment]
Will do as soon as I release a new stable version!

**Comment by uipko** [comment]
:+1:

**Pull request merged**
