### PR TITLE
Add support for ZRX on GDAK

### PR DESCRIPTION
**Pull request by g1tt**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds support for ZRX on GDAX - USD, ETH and BTC

### CODE REVIEW

**Comment by g1tt** [comment]
Mike - my apologies! Still working out git here.
I have a different mod under test and realised that submitting this (ZRX support) would submit my other mods as well.
So whilst it's a bit messy the end result should be that just the ZRX mods are submitted and my other mods stay here!
Won't do it again, promise! :)

**Comment by askmike** [comment]
No problem! Thanks for the fix.

**Comment by askmike** [comment]
TODO for next time:

Gekko is able to build an object of all supported markets, it does this for other exchanges already (binance, kraken, coinfalcon). Here is an example: https://github.com/askmike/gekko/blob/develop/exchange/util/genMarketFiles/update-binance.js

Based on this endpoint we can do the same for coinbase: https://api.pro.coinbase.com/products

**Comment by g1tt** [comment]
Thanks for the commit and the pointer. Leave it with me and I will sort out an update-coinbase.js file! :)

**Pull request merged**
