### PR TITLE
Expose Strategies to Trade Data

### PR DESCRIPTION
**Pull request by werkkrew**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)

Strategies cannot easily get trade events

* **What is the new behavior (if this is a feature change)?**

Strategies can now receive trade events when they are emitted.  If a strategy has an "onTrade" method, it will be executed any time there is a new trade which occurs.  An example strategy using this method can be found in strategies/CCI-custom.js, included in this PR.

* **Other information**:

If a strategy does not have an 'onTrade' method, no existing functionality is currently changed or broken in any way.

### CODE REVIEW

**Comment by werkkrew** [comment]
Reverted the commit which added the portfolio manager changes.  I will likely release a separate PR for those changes although it is a bit more complicated than I had first thought.

I realized that the method I used would be pretty quirky.  Gekko manages the portfolio balance 100% using the API, it does not store the balance anywhere or do any math against it.  Therefore what I was trying to do would behave strangely since it would do the math dynamically any time it got the balance.  This means if a partially filled order was cancelled and re-submitted it would re-calculate how much to sell for.  Also, if running multiple instances of the bot against the same asset, it would behave strange as well.

The trading data in strategies changes are functional and all that this PR is scoped for now.

**Comment by werkkrew** [comment]
This is tested and works except the portfolio data is not initialized as early as I would hope.

As is mentioned in https://github.com/askmike/gekko/issues/1541 I will either implement a workaround or ideally have the initial broadcast of the portfolio emit until after the plugins are initialized.

**Comment by billymcintosh** [comment]
Have also tested over the last few days.   Works well enough, and as you say, the portfolio data does take a bit longer than other strategies for some reason.

**Review by cmroche — APPROVED** [review]

**Comment by werkkrew** [comment]
I'd like to see if we can get the porfolio data into the strat before it starts trading, as early as possible.  Before merging this PR I'd also like people more familiar with the core project to make sure I impelemented it in the correct way in the correct places.

**Comment by billymcintosh** [comment]
Good shout.   With this branch rebased on a 'clean' `develop` branch and running a backtest on a regular CCI strategy,  sqlite throws an error. 

`gekko/node_modules/sqlite3/lib/trace.js:27`
`RangeError: Maximum call stack size exceeded`
`gekko/plugins/tradingAdvisor/baseTradingMethod.js:341`

It appears it's trying to select too much data.   I've only got one week in my sqlite database.

**Comment by billymcintosh** [comment]
Also..  how does this strategy know what my last purchase was for an asset? 

```2018-01-07 18:06:59 (DEBUG):	Trend:  overbought  for  1
2018-01-07 18:06:59 (DEBUG):	calculated CCI properties for candle:
2018-01-07 18:06:59 (DEBUG):		 Price:		 0.00016998
2018-01-07 18:06:59 (DEBUG):		 CCI tp:	 0.00016901
2018-01-07 18:06:59 (DEBUG):		 CCI tp/n:	 0.00016556
2018-01-07 18:06:59 (DEBUG):		 CCI md:	 0.00000130
2018-01-07 18:06:59 (DEBUG):		 CCI:		 176.39
2018-01-07 18:06:59 (INFO):	CCI Says to SELL!
2018-01-07 18:06:59 (INFO):	Sell conditions are NOT met and SAFETY is ON!
2018-01-07 18:06:59 (INFO):	TRADE WILL NOT EXECUTE!
2018-01-07 18:06:59 (INFO):	Buy Price:	 0.00021989
2018-01-07 18:06:59 (INFO):	Proposed Sell Price:	 0.00016998
2018-01-07 18:06:59 (INFO):	Proposed Profit:	 -29.36 %
2018-01-07 18:06:59 (INFO):	Required Profit:	 3.50 %
```
XBT/XRP on Kraken.   It seems to stop trading at midnight UTC on 5th January.    I've not purchased any XRP or XBT and restarted the server fresh. 

From looking at this more it appears the strategy is trying to sell XRP which I have none of!  

Any ideas?

**Comment by werkkrew** [comment]
So I think that error was from an infinite loop because I'm doing it wrong.

I made some changes that should work, although I'm having trouble testing it.  Would love some assistance on that front.

**Comment by billymcintosh** [comment]
I have it running again and it has just done the 90 ticks of history...   I'll see how that goes overnight then test the changes tomorrow :+1:

**Comment by billymcintosh** [comment]
Kraken being down didn't help me in testing but have given it 14 hours so far with a 1% profit minimum.   

It still tries to buy XRP when all I have is XRP.    I think that buy resets it then it normalizes.   It has sold for EUR and bought back XRP again.    Logs haven't been saved so I'll continue checking to see if the safety works as expected.

**Comment by werkkrew** [comment]
I am closing this pull request as it is now in conflict and has not been adequately tested.  I may re-submit it once I am able to do further testing.

**Pull request closed without merging**
