### PR TITLE
Add time sycnronization with Binance servers

### PR DESCRIPTION
**Pull request by cmroche**
A simple system wich asks Binance for their server time and stores the drift value every 5 minutes. This should help overcome many of the error 400 problems binance users are recently seeing. Addresses #1663 and #1712

### CODE REVIEW

**Comment by LobodaCrypto** [comment]
Yes, this is right method.
Solved successfully about error 400 in binance1.3.0
Thanks

**Comment by askmike** [comment]
@cmroche once again great work :)

**Comment by storshun** [comment]
So, this re-introduced more error 400s on my install after grabbing latest of binance and gekko. I mean, I know it was really just a one-line change, but I've had to comment it out to get my bot stable again.

**Comment by cmroche** [comment]
@storshun Can you give a debug log please, I was testing this in live this morning and didn't have any issues placing orders. Knowing which function is causing the issue, and the debug log with the server response will help validate if this is related to the problem (and why).

**Comment by storshun** [comment]
> 2018-01-21 15:22:15 (DEBUG):	[binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
> 2018-01-21 15:22:15 (INFO):	Attempting to BUY 5.236741764603258 NEO at binance price: 0.125712
> 2018-01-21 15:22:15 (DEBUG):	[binance.js] (addOrder) BUY 5.23 NEO @0.12571199 ETH
> 2018-01-21 15:22:16 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: Response code 400
> 2018-01-21 15:22:16 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: [binance.js] Response code 400 data: {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}
>

I've only been able to complete one roundtrip at most since the update, even commenting out the time sync. In fact, the error I posted above may have been sans timesync. I'm going back in my other logs to see if I can find the problem again.

**Comment by storshun** [comment]
@cmroche Looking at the error code I received on the log prior to me commenting out the binance time sync line, it appears to be the same error.

Also, this is the line I commented out;
` //this.binance.startTimeSync();`

> 2018-01-21 08:52:25 (DEBUG):	[binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
> 2018-01-21 08:52:25 (INFO):	Attempting to BUY 5.17952555002157 NEO at binance price: 0.127153
> 2018-01-21 08:52:25 (DEBUG):	[binance.js] (addOrder) BUY 5.17 NEO @0.12715299 ETH
> 2018-01-21 08:52:26 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: Response code 400
> 2018-01-21 08:52:26 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: [binance.js] Response code 400 data: {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}

**Comment by ghost** [comment]
Branch: Develop
Causes mine to crash after the purchase goes through - using ubuntu 
RECEIVED ERROR IN GEKKO 679074390134006


Gekko encountered an error and can't continue


Gekko encountered an error and can't continue

Error:

[binance.js] Response code 400

Meta debug info:

Gekko version: v0.5.12
Nodejs version: v9.3.0





2018-01-21 16:56:44 (DEBUG):	[binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
2018-01-21 16:56:44 (INFO):	Attempting to BUY 0.006276138848123633 XMR at binance price: 0.3311
2018-01-21 16:56:44 (DEBUG):	[binance.js] (addOrder) BUY 0.006 XMR @0.3321 ETH
2018-01-21 16:56:45 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: Response code 400

**Comment by cmroche** [comment]
@storshun Your experiencing something along the lines of #1703 now. PR #1550 should in theory fix this, and was just merged to develop. Sync the develop branch (don't forget to run `npm install`) and try again please.

**Comment by cmroche** [comment]
@storshun Your issue looks like #1703 now (well very similar). PR #1550 should address this issue and I think will be merged soon.

**Comment by ghost** [comment]
@cmroche nvm my issue was caused by folder write permissions chmod 777 fixed. <3

**Comment by christhecanadien** [comment]
Hi team,
Following the merge @askmike did 11 hours ago, I've just downloaded the last develop branch and Binance doesn't appear anymore in the UI neither in the "config" (install API keys) nor in the "live" tab (select the exchange for trading in) :(
capture d ecran 2018-01-21 a 20 18 28

**Comment by cmroche** [comment]
Issue is known now #1757, please track it there. I'll look into this shortly, likely an error in a recent merge.

**Pull request merged**
