### PR TITLE
add in candle vwap et nb trades

### PR DESCRIPTION
**Pull request by julesGoullee**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Everyone have their strategies, vwap and counter trades of candles are usefully !

### CODE REVIEW

**Comment by askmike** [comment]
Hey! Nice that you are going through that (messy & undocumented code), but the `this.candleProps` is only used to properly populate TAlib indicators. And some of them are using volume (you just fixed a bug!), but none are using `vwp` or `trades`. So there is no point in populating and maintaining these arrays.

**Comment by askmike** [comment]
Here you can find all TAlib indicator implementations: https://github.com/askmike/gekko/blob/1c0700d312e3f6bc6e4fb9f4d1fdcda5d3392736/core/talib.js

----

Would you mind changing this to just extend the volume array, but not the other ones?

**Comment by julesGoullee** [comment]
Not very messy ;),I've already find /core/talib.js, In substance I added method for use async strategy (ipc) and I need this props. I think the messy code is in baseTradingMethod, in my opinion it was the simple way for add custom async strategy, if you have a better idea I take it !

**Comment by askmike** [comment]
Fair enough, the candleProps arrays are only a 1000 elements anyway :)

**Comment by julesGoullee** [comment]
Yep, I show this, but why is not the warmup props length, I'm not understand

**Comment by askmike** [comment]
Good question actually! I have a *feeling* that people will try to get away with the lowest historySize (warmup period) as possible to not have to wait as long. But the overhead of storing a few more array items is pretty small. But the 1000 is quite randomly chosen by me, you are right..

**Comment by thegamecat** [comment]
This is related to: https://github.com/askmike/gekko/issues/891

**Comment by askmike** [comment]
@thegamecat fair point, I have responded there.

**Comment by thegamecat** [comment]
Ok so as far as design decisions go it seems clear there are people who want access to the candle data. We can agree on that for sure.

Why don't you want people accessing the candleprops data? Or perhaps rather, what is your preferred method of giving access to that data?

**Comment by askmike** [comment]
No: I am proposing a config flag that only exposes the candleProps to the
people who specifically want it, and not for everyone. As far as I know
there are 2 people who want this specific data and 4000 people who
installed gekko in the last month. No reason to decrease performance (speed
and memory usage) for all these people while we can make everyone
(including you) happy with a simple config switch.

**Comment by thegamecat** [comment]
Oh I see. There might be another way then, because in the UI you're writing all this data again to build the graphs. Maybe that and candleprops can be unified?

Just for the record the speed and memory impact is absolutely tiny. I did however notice that writing the candles and roundtrip to files does slow things down, particularly the candles (as one would expect).

**Comment by askmike** [comment]
>  because in the UI you're writing all this data again to build the graphs. Maybe that and candleprops can be unified?

The graphs only use the close of the candles no other properties. Also this is completely decoupled from a backtest for a few different reasons (including a bug you encountered where the backtest output was to big).

**Comment by LooOOooM** [comment]
great guy, and where is finally the swtich -- I upgraded gekko after about 6 -8 month and finally my strat which used candleProps is not working anymore as it tells me undefinded.

- how can I enable candleProbs again?

**Comment by medozero** [comment]
i need access to the previous candle(s) :) as well . so mike make them 4 ppl who will be happy including LooOOooM

**Comment by IAMtheIAM** [comment]
I also need to access previous candles, where is the flag to enable `candleProps` or how can I expose it manually to my strategy?

UPDATE: I figured it out.
Here's how you do it, as long as you are using a TALib indicator:

`let candleProps = this.asyncIndicatorRunner.candleProps`

This is quoted from [an article](http://gekkowarez.com/tag/candleprops/) which helped me:

> If you want to use the candleprops array in a non talib using Strategy then do the following:
> 
> open plugins/baseTradingMethods.js and commend out the line below and the corresponding close bracket:
> 
> // if(this.asyncTick) {
> 
> Then go to your strategy and write console.log(this); in the update method and look for the candleprops arrays.
> 
> Note: baseTradingMethod is a core Gekko file so you should make this change only if you’re comfortable managing this change yourself.

**Comment by askmike** [comment]
@IAMtheIAM the data behind those properties is only collected when you add certain indicators. The proper way is to store them yourself in your strategy.

**Pull request merged**
