### PR TITLE
Bitfinex - Move to new retry and error handling scheme, improvements to import

### PR DESCRIPTION
**Pull request by cmroche**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature

* **What is the current behavior?** (You can also link to an open issue here)

Retry and error handling is sparse, errors cause non-ending retries in some cases, and abort in others. Normalizing errors is not consistent between function calls.

* **What is the new behavior (if this is a feature change)?**

Moving Bitfinex to using the new pattern for retry and error handling, similar to that of Kraken. This is not tested yet in live trading and should be validated with someone who actively uses live trading on this exchange.

Minor improvements to the importer to make it tolerant to errors, and improve scanning speed in time-ranges where there are not active trades happening.

Add retry handling for HTTP 429 (rate limit) and select HTTP 500 errors.

Tested import, paper trade

### CODE REVIEW

**Comment by Paulovms** [comment]
@cmroche I’ve got this error when I tried to import using command line.
```
/root/gekko/importers/exchanges/bitfinex.js:79
    batch_end = moment(from).add(stride, 'h');
                                 ^

ReferenceError: stride is not defined
    at Object.fetch (/root/gekko/importers/exchanges/bitfinex.js:79:34)
    at Market.get (/root/gekko/core/markets/importer.js:95:16)
    at Market.bound [as get] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Market (/root/gekko/core/markets/importer.js:80:8)
    at /root/gekko/core/pipeline.js:187:20
    at /root/gekko/node_modules/async/dist/async.js:3853:9
    at /root/gekko/node_modules/async/dist/async.js:484:16
    at replenish (/root/gekko/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at prepareMarket (/root/gekko/core/pipeline.js:164:7)
    at /root/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/root/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at subscribePlugins (/root/gekko/core/pipeline.js:156:5)
```

**Comment by cmroche** [comment]
@Paulovms var stride is defined at the top scope level in the .js file, this error should only be possible if there was a bad merge and that line is missing when you grabbed the change, please check and confirm.

**Review by askmike — APPROVED** [review]

**Comment by askmike** [comment]
thanks!

**Comment by big-striped-cat** [comment]
@cmroche I have a problem with import to Postgresql

I started Gekko CLI in import mode with postgresql adapter
> gekko --config config.js --import

Console output looks like everything was ok, but no candle data appeared in DB table.
The problem is that Node process exits before DB connection callbacks are run.

 This code in `Gekko.prototype.shutdown` forces parent process to exit.
```js
Gekko.prototype.shutdown = function() {
  this.end();
  async.eachSeries(
    this.plugins,
    function(c, callback) {
      if (c.finalize) c.finalize(callback);
      else callback();
    },
    () => {
      // If we are a child process, we signal to the parent to kill the child once it is done
      // so that is has time to process all remaining events (and send report data)
      if (env === 'child-process') process.send('done');
      else process.exit(0);
    }
  );
};
```

Postgresql adapter is async. One can not rely that all insertions are made at the time of calling `writer.finalize`. Previous insertions are made with `writer.writeCandles` which is not supplied with callback . Calling `process.exit` prevents DB insertion to be executed.

Sqlite adapter is synchronous, so the problem does not reproduce for sqlite.

When I removed `process.exit` the import worked fine both for postgres and sqlite.

What was the point of manual exiting here?

**Pull request merged**
