### PR TITLE
HOTFIX fixed readme docker image

### PR DESCRIPTION
**Pull request by ivan1993spb**
- [Dockerfile](https://github.com/ivan1993spb/docker-gekko/blob/master/Dockerfile)
- [Repo](https://github.com/ivan1993spb/docker-gekko)
- [Image](https://hub.docker.com/r/ivan1993spb/gekko/)

### CODE REVIEW

**Comment by askmike** [comment]
Is the other one broken?

**Comment by ivan1993spb** [comment]
No it is not, but the old Dockerfile is incorrect and doesn't have additional jsnode dependencies and so the old image is useless

**Comment by askmike** [comment]
ping @BarnumD

**Comment by BarnumD** [comment]
I've updated my docker container to contain talib and pg.  Were there other dependencies that you needed?

**Comment by ivan1993spb** [comment]
@BarnumD Yes. Could you create `VOLUME` for gekko history folder

**Comment by BarnumD** [comment]
Done. @ivan1993spb

**Pull request closed without merging**
