### PR TITLE
Fix GDAX importing

### LINKED ISSUE #1325: GDAX Import keeps erroring out
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running import of 6 week timespan

* **Expected result** (what you hoped would happen)
data import

* **Actual result** (unexpected outcome)
Partial data import. Child process dies. Ubuntu Linux 16.04-64bit. Insured system is not going to sleep. Console output:

> <-- POST /api/scansets
>   --> POST /api/scansets 200 831ms 124b
> /opt/gekko/exchanges/gdax.js:262
>                 log.debug('Backwards: ' + last.time + ' (' + last.trade_id + ') to ' + first.time + ' (' + first.trade_id + ')');
>                                                ^
> 
> TypeError: Cannot read property 'time' of undefined
>     at Trader.<anonymous> (/opt/gekko/exchanges/gdax.js:262:48)
>     at Request._callback (/opt/gekko/node_modules/gdax/lib/clients/public.js:45:7)
>     at Request.self.callback (/opt/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
>     at Request.emit (events.js:159:13)
>     at Request.<anonymous> (/opt/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
>     at Request.emit (events.js:159:13)
>     at IncomingMessage.<anonymous> (/opt/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
>     at IncomingMessage.emit (events.js:164:20)
>     at endReadableNT (_stream_readable.js:1054:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> RECEIVED ERROR IN IMPORT 290458505747063
> Child process has died.

* **Other information**
I have tried this numerous times and it continues to fail.

### PR DESCRIPTION
**Pull request by cmroche**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

BugFix

* **What is the current behavior?** (You can also link to an open issue here)

GDAX importing will often halt, depending on the date ranges selected. This is due to rate-limit errors throwing an exception and killing the import process.

* **What is the new behavior (if this is a feature change)?**

Added a check for REST errors and passed the getTrades request into the retry handler.

* **Other information**:

A better approach is probably to fix the backscanning process to use timers and prevent a flood of requests. GDAX allows a consistent 3 queries per second, so we could easily work around this.

However the GDAX exchange could probably use a pass and a clean up and normalization of the error handling in the future. For now this quick fix is probably the least risky approach to fixing the import problems some people are reporting.

Should fix #1325 #1295 and #606

### CODE REVIEW

**Comment by lavere** [comment]
Gdax imports were failing for me and this fixed it.

**Comment by askmike** [comment]
:+1:

**Comment by hulu1522** [comment]
GDAX imports are still failing for me on current develop branch.

**Comment by askmike** [comment]
Can you post logs?

**Comment by hulu1522** [comment]
@askmike How would you like me to collect them?  Is there a way to get debug logs?  Right now it will fail sometimes and then others is just sits there and doesn't start downloading.  In both cases nothing is downloaded.

**Comment by hulu1522** [comment]
@askmike Also, these are being started from the UI... I'll try the cli also.

**Comment by GuyPaddock** [comment]
Here's what I'm seeing:
```
2017-12-08 04:06:18 (DEBUG):    GDAX returned an error, retrying..
2017-12-08 04:06:28 (DEBUG):    Scanning back in the history needed...
2017-12-08 04:06:28 (DEBUG):    2017-09-01T00:00:00+00:00
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T04:05:52.981Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T04:05:40.63Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T04:05:02.947Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T04:04:48.979Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T04:02:13.525Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T04:00:21.642Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T03:57:10.894Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T03:53:41.281Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T03:50:39.983Z
2017-12-08 04:06:28 (DEBUG):    Scanning backwards...2017-12-08T03:47:48.443Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:45:43.965Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:42:53.28Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:40:53.396Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:37:10.78Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:34:12.274Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:31:21.995Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:30:23.679Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:27:41.932Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:22:38.757Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:20:18.832Z
2017-12-08 04:06:29 (DEBUG):    Scanning backwards...2017-12-08T03:16:29.241Z
2017-12-08 04:06:29 (DEBUG):    GDAX returned an error, retrying..
... time passes ...
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:07:07.107Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:07:04.909Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:06:45.978Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:05:35.47Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:04:52.026Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:01:59.419Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T04:00:08.765Z
2017-12-08 04:07:21 (DEBUG):    Scanning backwards...2017-12-08T03:56:12.532Z
2017-12-08 04:07:22 (DEBUG):    Scanning backwards...2017-12-08T03:52:40.403Z
2017-12-08 04:07:22 (DEBUG):    Scanning backwards...2017-12-08T03:48:58.778Z
2017-12-08 04:07:22 (DEBUG):    Scanning backwards...2017-12-08T03:46:56.641Z
2017-12-08 04:07:22 (DEBUG):    Scanning backwards...2017-12-08T03:44:00.466Z
2017-12-08 04:07:22 (DEBUG):    Scanning backwards...2017-12-08T03:41:31.201Z
2017-12-08 04:07:22 (DEBUG):    Scanning backwards...2017-12-08T03:38:36.977Z
2017-12-08 04:07:22 (DEBUG):    GDAX returned an error, retrying..
2017-12-08 04:07:32 (DEBUG):    Scanning back in the history needed...
2017-12-08 04:07:32 (DEBUG):    2017-09-01T00:00:00+00:00
2017-12-08 04:07:32 (DEBUG):    Scanning backwards...2017-12-08T04:07:11.053Z
2017-12-08 04:07:32 (DEBUG):    Scanning backwards...2017-12-08T04:07:04.909Z
2017-12-08 04:07:32 (DEBUG):    Scanning backwards...2017-12-08T04:06:58.655Z
2017-12-08 04:07:32 (DEBUG):    Scanning backwards...2017-12-08T04:05:40.63Z
2017-12-08 04:07:32 (DEBUG):    GDAX returned an error, retrying..
```

**Comment by hulu1522** [comment]
Yep, looks like I'm seeing the same thing.
```
2017-12-07 21:10:33 (DEBUG):	Scanning backwards...2017-12-08T02:40:31.998Z
2017-12-07 21:10:33 (DEBUG):	GDAX returned an error, retrying..
2017-12-07 21:10:43 (DEBUG):	Scanning back in the history needed...
2017-12-07 21:10:43 (DEBUG):	2017-11-01T00:00:00Z
2017-12-07 21:10:43 (DEBUG):	Scanning backwards...2017-12-08T04:10:39.823Z
2017-12-07 21:10:44 (DEBUG):	Scanning backwards...2017-12-08T04:10:22.531Z
2017-12-07 21:10:44 (DEBUG):	Scanning backwards...2017-12-08T04:09:05.435Z
2017-12-07 21:10:44 (DEBUG):	Scanning backwards...2017-12-08T04:07:54.83Z
2017-12-07 21:10:44 (DEBUG):	Scanning backwards...2017-12-08T04:07:12.738Z
2017-12-07 21:10:45 (DEBUG):	Scanning backwards...2017-12-08T04:05:57.645Z
2017-12-07 21:10:45 (DEBUG):	Scanning backwards...2017-12-08T04:04:51.394Z
2017-12-07 21:10:45 (DEBUG):	Scanning backwards...2017-12-08T04:00:31.837Z
2017-12-07 21:10:45 (DEBUG):	Scanning backwards...2017-12-08T03:57:22.526Z
2017-12-07 21:10:46 (DEBUG):	Scanning backwards...2017-12-08T03:52:57.682Z
2017-12-07 21:10:46 (DEBUG):	GDAX returned an error, retrying..
2017-12-07 21:10:56 (DEBUG):	Scanning back in the history needed...
2017-12-07 21:10:56 (DEBUG):	2017-11-01T00:00:00Z
2017-12-07 21:10:56 (DEBUG):	Scanning backwards...2017-12-08T04:10:42.519Z
2017-12-07 21:10:57 (DEBUG):	Scanning backwards...2017-12-08T04:10:36.979Z
2017-12-07 21:10:57 (DEBUG):	Scanning backwards...2017-12-08T04:09:28.889Z
2017-12-07 21:10:57 (DEBUG):	Scanning backwards...2017-12-08T04:08:10.67Z
2017-12-07 21:10:57 (DEBUG):	Scanning backwards...2017-12-08T04:07:35.676Z
2017-12-07 21:10:58 (DEBUG):	Scanning backwards...2017-12-08T04:06:35.922Z
2017-12-07 21:10:58 (DEBUG):	GDAX returned an error, retrying..
2017-12-07 21:11:08 (DEBUG):	Scanning back in the history needed...
2017-12-07 21:11:08 (DEBUG):	2017-11-01T00:00:00Z
```

I guess what should really happen is a percentage bar showing the progress of scanned dates.  That way people will know how close it is to finishing the back scan and starting the download.  What would be even better is to start a child process that will start downloading as dates are scanned.  I assume downloading and scanning are different steps of the importing process.

**Comment by hulu1522** [comment]
@askmike Okay, I did a little more digging into the code and it looks like GDAX is enforcing a rate limit which is causing all of these error.
```
    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.5.10
	I'm gonna make you rich, Bud Fox.


2017-12-07 21:41:44 (INFO):	Setting up Gekko in importer mode
2017-12-07 21:41:44 (INFO):
2017-12-07 21:41:44 (INFO):	Setting up:
2017-12-07 21:41:44 (INFO):		 Candle writer
2017-12-07 21:41:44 (INFO):		 Store candles in a database
2017-12-07 21:41:44 (INFO):

2017-12-07 21:41:44 (DEBUG):	Check database exists: devDB
2017-12-07 21:41:44 (DEBUG):	Database exists: devDB
2017-12-07 21:41:44 (DEBUG):	Postgres connected to devDB
2017-12-07 21:41:44 (DEBUG):	No end date specified for importing, setting to 2017-12-08 04:41:44
2017-12-07 21:41:44 (DEBUG):	Scanning back in the history needed...
2017-12-07 21:41:44 (DEBUG):	2017-11-01T00:00:00Z
2017-12-07 21:41:45 (DEBUG):	null
2017-12-07 21:41:45 (DEBUG):	Scanning backwards...2017-12-08T04:41:36.111Z
2017-12-07 21:41:45 (DEBUG):	null
2017-12-07 21:41:45 (DEBUG):	Scanning backwards...2017-12-08T04:41:20.344Z
2017-12-07 21:41:45 (DEBUG):	null
2017-12-07 21:41:45 (DEBUG):	Scanning backwards...2017-12-08T04:40:51.917Z
2017-12-07 21:41:45 (DEBUG):	null
2017-12-07 21:41:45 (DEBUG):	Scanning backwards...2017-12-08T04:40:31.861Z
2017-12-07 21:41:46 (DEBUG):	null
2017-12-07 21:41:46 (DEBUG):	Scanning backwards...2017-12-08T04:40:00.406Z
2017-12-07 21:41:46 (DEBUG):	Error: Rate limit exceeded
    at Trader.<anonymous> (/opt/gekko/dev/exchanges/gdax.js:233:19)
    at Request._callback (/opt/gekko/dev/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/opt/gekko/dev/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/gekko/dev/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/gekko/dev/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
2017-12-07 21:41:46 (DEBUG):	GDAX returned an error, retrying..
```

**Comment by hulu1522** [comment]
And the actual problem is that GDAX only allows 3-6 requests per second.
```
PUBLIC ENDPOINTS

We throttle public endpoints by IP: 3 requests per second, up to 6 requests per second in bursts.
```
https://docs.gdax.com/#rate-limits


Sorry for all the comments, it's just an annoying issue.

**Comment by askmike** [comment]
Current Gekko implementation is basically a race condition against their rate limits (if the trades fetch takes longer than 0.33 sec gekko won't get rate limited, it will if the fetch is faster).

Will fix this, but it will make GDAX importing even slower than it already is..

**Comment by hulu1522** [comment]
@askmike One issue that I am seeing is that the "Scanning backwards" always starts from the current time and works backwards instead of starting from where it left off.  This is essentially causing a request loop so the importing will never actually download data, it will reset when it gets an error.
```
2017-12-07 22:37:30 (DEBUG):	Scanning backwards...2017-12-07T19:31:48.384Z
2017-12-07 22:37:31 (DEBUG):	Scanning backwards...2017-12-07T19:21:49.943Z
2017-12-07 22:37:31 (DEBUG):	GDAX returned an error, retrying..
2017-12-07 22:37:31 (DEBUG):	Scanning back in the history needed...
2017-12-07 22:37:31 (DEBUG):	2017-11-01T00:00:00Z
2017-12-07 22:37:32 (DEBUG):	Scanning backwards...2017-12-08T05:37:16.724Z
2017-12-07 22:37:32 (DEBUG):	Scanning backwards...2017-12-08T05:37:08.092Z
2017-12-07 22:37:32 (DEBUG):	Scanning backwards...2017-12-08T05:36:55.838Z
2017-12-07 22:37:32 (DEBUG):	Scanning backwards...2017-12-08T05:36:23.126Z
2017-12-07 22:37:32 (DEBUG):	Scanning backwards...2017-12-08T05:35:36.231Z
2017-12-07 22:37:33 (DEBUG):	GDAX returned an error, retrying..
2017-12-07 22:37:33 (DEBUG):	Scanning back in the history needed...
2017-12-07 22:37:33 (DEBUG):	2017-11-01T00:00:00Z
2017-12-07 22:37:33 (DEBUG):	Scanning backwards...2017-12-08T05:37:17.114Z
2017-12-07 22:37:33 (DEBUG):	Scanning backwards...2017-12-08T05:37:08.308Z
2017-12-07 22:37:34 (DEBUG):	Scanning backwards...2017-12-08T05:36:55.868Z
2017-12-07 22:37:34 (DEBUG):	Scanning backwards...2017-12-08T05:36:23.126Z
2017-12-07 22:37:34 (DEBUG):	Scanning backwards...2017-12-08T05:35:36.231Z
2017-12-07 22:37:34 (DEBUG):	Scanning backwards...2017-12-08T05:34:07.695Z
2017-12-07 22:37:34 (DEBUG):	Scanning backwards...2017-12-08T05:32:14.439Z
2017-12-07 22:37:35 (DEBUG):	Scanning backwards...2017-12-08T05:31:06.503Z
2017-12-07 22:37:35 (DEBUG):	Scanning backwards...2017-12-08T05:29:47.049Z
2017-12-07 22:37:35 (DEBUG):	Scanning backwards...2017-12-08T05:28:56.321Z
```

Maybe we need to implement an auto updating variable for the `before` and `after` variable.  That way every request will only start `after` the last pagination ID.  If the request has to be retried then you can add the `before` pagination ID so it only picks up what was missed.  Just thoughts, I'm not a programmer but like to fiddle.  Will help where I can.

**Comment by askmike** [comment]
yes you are 100% right, to sum up current todo:

- track current fetch time between errors.
- make sure we fetch after at least 0.33 seconds since last fetch (to always be under 3 req/sec).

**Comment by hulu1522** [comment]
👍 Thanks for all you are doing.

**Comment by askmike** [comment]
Np, but it's a group effort: GDAX was added by @smurfy and multiple people have fixed bugs and stabilized it after that :)

**Comment by outpoints** [comment]
Is anybody working on this? :(

**Comment by greenbigfrog** [comment]
@mew351 this should be fixed/done in the latest release. If you still encounter any issues after testing the latest develop branch feel free to open a issue

**Comment by outpoints** [comment]
@greenbigfrog I don't see any pulls in dev branch yet

**Comment by greenbigfrog** [comment]
@mew351 I'm assuming you just cloned the repo.
Run `git pull` and then `git checkout develop` to checkout the latest code.

**Comment by askmike** [comment]
@mew351 you are commenting on code getting added to gekko, here are the specific changes: https://github.com/askmike/gekko/pull/1397/files

This was merged into the develop version and later released as part of Gekko 0.5.11:

> [EXCHANGE] Fix GDAX importing (@cmroche - #1397)

**Comment by gigirk** [comment]
error is still present :(  Using Gekko v0.5.11 and Gekko UI v0.2.0.

Importing data..
Market:
gdax
Currency/Asset:
BTC/LTC
From:
2017-12-11 11:29:00
To:
2017-12-14 12:29:00

error in line 251
canot read property 'time' of undefined 

` if (moment.utc(last.time) < moment.utc(since)) {`

**Comment by greenbigfrog** [comment]
@gigirk your issue is unrelated to what was originally fixed in this PR. Please open a new issue with a full debug log.

**Comment by avinashn9** [comment]
github/gekko/exchanges/gdax.js:251
   
             if (moment.utc(last.time) < moment.utc(since)) {
                                    ^

TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (/Users//github/gekko/exchanges/gdax.js:251:37)
    at Request._callback (/Users//github/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/Users//github/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users//github/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users//github/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
RECEIVED ERROR IN IMPORT 168283852055861
Child process has died.


Any fix?

**Comment by cmroche** [comment]
@avinashn9 Pending PR #1543 re-implements GDAX using the new approach for error and retry handling, and will likely resolve this issue.

**Pull request merged**
